### ISSUE TITLE
Pfizer - The number of jobs posted on Peviitor isn't the same as the one posted on the company website.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#100]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Pfizer" in the search bar.
3. Check the number of jobs available for Pfizer.
4. Open "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers?locations=e2d3979e3af10101e2ff1f61076c1097".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website shoud be the same.

ACTUAL RESULT:
There are 5 jobs posted on Peviitor website while there are 3 job posted on the company website.

![pfizer peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/a586f216-1e39-4f73-bae8-50af0aea49ac)

![pfizer site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/5ee1f44e-9cf8-4711-8d41-327e6116ab93)

**Comment by Ale230992** [comment]
Acum sunt 6 Peviitor si 5 site-ul Pfizer

![pfizer peviitor reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/1dd00c66-77d4-440a-899f-327b48f87152)

![pfizer site reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/cc2c428c-e655-4294-a285-c150425dbc15)

**Comment by lalalaurentiu** [comment]
Selectează "Romania" nu doar București, de acea iti afișează doar 5 posturi

**Comment by Ale230992** [comment]
Abia acum am reusit, ca am scris tara, altfel, e by default "Romania-Bucharest".
Fixed, il inchid acum.
