### ISSUE TITLE
Atos - The number of jobs posted on Peviitor and the one posted on the company website isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#102]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Atos" in the search bar.
3. Check the number of jobs available for Atos.
4. Open "https://atos.net/en/careers?country=RO".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website shoud be the same.

ACTUAL RESULT:
There are 101 jobs posted on Peviitor website while on the company website there are 110 jobs posted.

![atos peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/3eec0fc3-315c-4a2e-8770-5ff6f6525d42)

![atos site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/e6e87bb8-fa15-447c-812b-39cf5ff83e1b)

**Comment by Ale230992** [comment]
I can't run the scraper because the server is down, but, the number of jobs on the company website has been again modified.

![atos site reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/cfa4c74b-091b-4fd7-83a0-dc74fa503fd3)

**Comment by TheMrM** [comment]
Modified the scraper to correctly show 108 jobs
![1](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/6f9897dc-b20d-4589-bb56-19572c05a8d2)
![2](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/cad4341a-3222-4e4d-8e81-2ebcb8d4216f)
