### ISSUE TITLE
Molson Coors - The number of jobs posted on Peviitor and the one posted on the company website isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#103]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Molson Coors" in the search bar.
3. Check the number of jobs available for Molson Coors.
4. Open "https://jobs.molsoncoors.com/MolsonCoors_GBSRomania/?locale=en_US".
5. Count the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website shoud be the same.

ACTUAL RESULT:
There are 34 jobs posted on Peviitor website while on the company website there are 32 available jobs.

![molsoncoors peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/2f513198-e273-4f05-808f-e47a6abc3748)

![molsoncoors site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/4ce58247-e05f-4142-a9e2-6a6eda60ee13)

**Comment by lalalaurentiu** [comment]
Asta e pagina de unde extrage scraper joburi https://jobs.molsoncoors.com/MolsonCoors_GBSRomania/search/?q=Romania&startrow=25
Numeral de joburi extrase sunt la fel ca cel de pe site, se mai găsesc situații unde apar alte tari dar dacă intram în descriere jobului scrie ca sunt disponibile și pe România.
<img width="1440" alt="Screenshot 2023-09-15 at 19 06 09" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/6703b3e5-2826-4007-a125-b29b88349055">
<img width="1440" alt="Screenshot 2023-09-15 at 19 06 50" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/ce573ca2-521f-4f2d-abf0-ed2c26a87a77">

<img width="1440" alt="Screenshot 2023-09-15 at 19 15 13" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/b44177e3-4590-4971-a8c7-d81077f8e637">
