### ISSUE TITLE
HP - The number of jobs posted on Peviitor and the one posted on the company website isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#109]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "HP" in the search bar.
3. Check the number of jobs available for HP.
4. Open "https://jobs.hp.com/search-results/?keyword=romania".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 15 jobs posted on Peviitor website while on the company website there are posted 17 available jobs.

![hp peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/85239823-81ed-499e-bfbf-0834eb74abcf)

![hp site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/a6a187bb-5180-4fd2-a05c-05597255b114)

**Comment by lalalaurentiu** [comment]
După repornirea screperulu îmi afișează acelasi număr de posturi.
<img width="1440" alt="Screenshot 2023-09-15 at 19 28 44" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/d13e5add-4f31-4cb3-bb10-cba59259e84e">
<img width="1440" alt="Screenshot 2023-09-15 at 19 28 31" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/91d74eaf-d7df-4eb4-b8bd-a1d8e39165e3">

**Comment by Ale230992** [comment]
da, acum numarul de pe scraper si Peviitor coincide cu cel de pe site-ul companiei. fixed, il inchid.
