### ISSUE TITLE
Weatherford - The number of jobs posted on Peviitor isn't the same as the number of jobs returned by the API.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#114]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Weatherford" in the search bar.
3. Check the number of jobs available for Weatherford.
4. Run "Weatherford" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 8 while the number of jobs returned by the API is 9.

![weatherford peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/b7a655b5-665e-43a5-879e-c10effa3698c)

![weatherford scraper](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/097c84d4-1503-4b85-ba25-0c4842970e0a)

**Comment by lalalaurentiu** [comment]
I don't think there is any problem!
<img width="1440" alt="Screenshot 2023-09-22 at 14 02 19" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/24ac4b7f-1a0b-43c0-91b6-ae77c337a515">
<img width="1440" alt="Screenshot 2023-09-22 at 14 01 58" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/b0e64b37-a1df-4259-894f-08296ab7453e">

**Comment by Ale230992** [comment]
Retested. Fixed. Closed issue.
