### ISSUE TITLE
AHK - The number of jobs posted on Peviitor and the one posted on the company website isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#123]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "AHK" in the search bar.
3. Check the number of jobs available for AHK.
4. Open "https://www.ahkrumaenien.ro/ro/cariere/vino-in-echipa-noastra".
5. Count the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 2 jobs posted on Peviitor website while on the company website there are posted 3 available jobs.

![ahk peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/e759751e-fc42-409d-8ff4-e80554f00a96)

![ahk site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/57d3ac9d-815b-4913-a4d4-c6a54f321b26)

**Comment by lalalaurentiu** [comment]
Fixed!
