### ISSUE TITLE
Randstad - The number of jobs posted on Peviitor (15) and the one posted on the company website (17) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#124]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Randstad" in the search bar.
3. Check the number of jobs available for Randstad.
4. Open "https://www.randstad.ro/locuri-de-munca/lucreaza-la-randstad/".
5. Count the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 15 jobs posted on Peviitor website while on the company website there are posted 17 available jobs.

![randstad peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/27ee3b8a-49f4-4ace-a4b6-7cc7bd6ed5e7)

![randstad site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/e7b3ecdd-41e4-48b0-98ba-27603cdffc10)

**Comment by lalalaurentiu** [comment]
Before start testing go to [https://scrapers.peviitor.ro](url)
in search bar type "randstad"
click on randstand folder 
click on "run scraper" 
wait to scraper to finish
and compare the results 
I tested it and the scraper returns the same result
<img width="1440" alt="Screenshot 2023-09-26 at 07 49 20" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/dfa49185-a3af-4da9-abc9-3b215c100527">
<img width="1440" alt="Screenshot 2023-09-26 at 07 49 23" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/127cfc5c-89e6-4038-9e37-195c9e12e045">
