### ISSUE TITLE
Gep - The number of jobs posted on Peviitor (21) and the one posted on the company website (24) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#126]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Gep" in the search bar.
3. Check the number of jobs available for Gep.
4. Open "https://jobseurope-gep.icims.com/jobs/search?ss=1&searchRelation=keyword_all&searchLocation=13526--".
5. Count the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 21 jobs posted on Peviitor website while on the company website there are posted 24 available jobs.

![gep peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/abb713ee-d63d-451a-bee9-ed5e5b3ca485)

![gep site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/a94e0e4e-b9df-4202-8b7a-2d4b93ad57ee)

**Comment by lalalaurentiu** [comment]
Fixed!
