### ISSUE TITLE
GoodYear - The number of jobs posted on Peviitor (25) and the one posted on the company website (31) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#127]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "GoodYear" in the search bar.
3. Check the number of jobs available for GoodYear.
4. Open "https://jobs.goodyear.com/search/?createNewAlert=false&q=&locationsearch=romania".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 25 jobs posted on Peviitor website while on the company website there are posted 31 available jobs.

![good year peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/5743f9d3-34d2-45f2-8334-66e19fee4ed4)

![goodyear site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/a072db40-1029-44c1-ae15-3b6615e84b0e)

**Comment by lalalaurentiu** [comment]
Fixed!
