### ISSUE TITLE
Renault - The number of jobs posted on Peviitor (143) and the one posted on the company website (140) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#128]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Renault" in the search bar.
3. Check the number of jobs available for Renault.
4. Open "https://alliancewd.wd3.myworkdayjobs.com/ro-RO/renault-group-careers?locationCountry=f2e609fe92974a55a05fc1cdc2852122&workerSubType=62e55b3e447c01871e63baa4ca0f9391&workerSubType=62e55b3e447c01140817bba4ca0f9891&workerSubType=62e55b3e447c01d10acebaa4ca0f9691".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 143 jobs posted on Peviitor website while on the company website there are posted 140 available jobs.

![renault peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/d2550b47-99fa-46b0-b259-3c6f974d96b7)

![renault site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/66f93d01-03e8-40b7-b0db-f61cead16a9c)

**Comment by lalalaurentiu** [comment]
Fixed!
