### ISSUE TITLE
ADOBE - Job no longer accessible on company's website

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_py#132]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

    1.  Open URL in the browser
    2.  Type  "Adobe" in search bar
    3.  Click on the "Account Director Chile" job title
    4.  Verify if the job is displayed on the company website
    
EXPECTED RESULTS:
The "Account Director Chile" job that is available on the peviitor platform should also be accessible and available on the company's website.

ACTUAL RESULTS:
The job that is available on peviitor is no longer accessible on the company's website.

![adobe](https://github.com/peviitor-ro/based_scraper_py/assets/135150327/1e008a28-95c3-4784-9159-e8df5bca80d5)

**Comment by lalalaurentiu** [comment]
This post is not longer available on peviitor!
<img width="1440" alt="Screenshot 2023-09-28 at 07 10 02" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/a0a31d93-b676-4a4f-8d0e-ff627354956d">
