### ISSUE TITLE
Incorrect country for job: peviitor specification vs. company website

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_py#138]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Type "Adobe" in the search bar
  3. Go to the "Senior Administrative Assistant" job title and click on it
  4. Verify on the company website if the country specified for the job is Romania

EXPECTED RESULTS:
The specified country for the job listing on the company website should match the country specified on the peviitor platform.

ACTUAL RESULTS:
The specified country for the job listing on the company website differs from the country specified on the peviitor platform.

![Screenshot 2023-09-14 175823](https://github.com/peviitor-ro/based_scraper_py/assets/135150327/d0181a3c-ae1c-4d16-96d5-38f0a947d9d2)

![Screenshot 2023-09-14 175854](https://github.com/peviitor-ro/based_scraper_py/assets/135150327/f0cb5fed-0773-4159-9dee-1aad0a7fe36b)

**Comment by lalalaurentiu** [comment]
This post is not longer available on peviitor!
<img width="1440" alt="Screenshot 2023-09-28 at 07 33 35" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/487933d5-a2e7-42da-9c4a-3f1c63cffe66">
