### ISSUE TITLE
Infineon - The number of jobs posted on Peviitor (28) and the one posted on the company website (27) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#145]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Infineon" in the search bar.
3. Check the number of jobs available for Infineon.
4. Open "https://www.infineon.com/cms/en/careers/jobsearch/jobsearch/#!view=jobs&country=Romania".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 28 jobs posted on Peviitor website while on the company website there are posted 27 available jobs.

![infineon peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/093b6d03-8af3-4334-b380-fedcae008834)

![infineon site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/cccb11c2-4987-4257-9372-b9ac69d3054f)

**Comment by lalalaurentiu** [comment]
I don't think there is any problem!
<img width="1440" alt="Screenshot 2023-09-29 at 07 10 25" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/611bd0c6-0748-4e8e-95e9-ff775b9ac427">
<img width="1440" alt="Screenshot 2023-09-29 at 07 10 31" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/79039d9b-46cc-4609-98d0-1e2ee82bf4b6">
<img width="1440" alt="Screenshot 2023-09-29 at 07 11 27" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/8bae087e-f062-466a-8a45-469046889857">
