### ISSUE TITLE
Autonom - Testul are un rezultat diferit 24 fata de joburile de pe peviitor.ro 20 si siteul autonom 20, deci probabil este o problema cu testul.

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#15]
Testul are un rezultat diferit 24 fata de joburile de pe peviitor.ro 20 si siteul autonom 20, deci probabil este o problema cu testul.

**Comment by lalalaurentiu** [comment]
Am reușit să rezolv problema afișării a celor 24 de joburi date de scraper, în loc de cele 20 pe care site-ul de cariere le prezintă inițial.
