### ISSUE TITLE
FORTECH - Job not found 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#154]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to Fortech - Business Analyst
  3. Check the job on the Fortech website - https://www.fortech.ro/job-openings/business-analysts

EXPECTED RESULT:
The job is valid

ACTUAL RESULT:
The job exists on the company's website, but it disappears when  want to apply for this job

**Comment by TheMrM** [comment]
FORTECH was not made with python

**Comment by lalalaurentiu** [comment]
Fortech is on python now, is fully working  
<img width="1440" alt="Screenshot 2023-09-29 at 07 25 12" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/39a613bf-ca38-4e2e-9c27-1973f80c601d">
<img width="1440" alt="Screenshot 2023-09-29 at 07 25 44" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/0ab0278f-8af8-4a1d-80a0-dc9e8b34d6ff">
