### ISSUE TITLE
Job not found on the company website - QuantRabbit - Customer Support Agent

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#157]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in the browser
2. Go to "quantrabbit - Customer Support Agent"
3. Open Quantrabbit website
4. Check if the "Customer Support Agent" job exists on the Quantrabbit website

EXPECTED RESULTS:
The "Customer Support Agent" job exists on the company's website and is valid

ACTUAL RESULTS:
The job "Customer Support Agent" does not exist on the company website

**Comment by lalalaurentiu** [comment]
That post does not exist on the peviitor site!
<img width="1440" alt="Screenshot 2023-09-29 at 07 31 16" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/85e4abd0-191f-402c-9e06-945df48a1a69">
