### ISSUE TITLE
The job is from 2017 - Quantrabbit - Trading Operator (Night Shift)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#158]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in the browser
2. Go to "quantrabbit - Trading Operator (Night Shift) "
3. Open Quantrabbit website
4. Check if the "Trading Operator (Night Shift)" job is valid on the Quantrabbit website

EXPECTED RESULTS:
The "Trading Operator (Night Shift)" job exists on the company's website and is valid

ACTUAL RESULTS:
The job "Trading Operator (Night Shift)" exists on the company website but the job is from 2017

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/8457e98e-2af7-46ba-9e02-b9a48a2dc7fd)

**Comment by lalalaurentiu** [comment]
being still displayed and not deleted from the site, we put it as valid!
