### ISSUE TITLE
Company not found - TEKINSPORTS

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#159]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open URL in the browser
 2. Go to "TEKINSPORTS" Company
 3. Open TEKINSPORTS website

EXPECTED RESULTS:
The TEKINSPORTS website opens and active jobs can be checked

ACTUAL RESULTS:
The TEKINSPORTS website cannot be found and active jobs cannot be checked

**Comment by TheMrM** [comment]
Removed the expired job. The company should automatically delete.

**Comment by lalalaurentiu** [comment]
This company is no longer on the peviitor website
<img width="1440" alt="Screenshot 2023-09-29 at 07 41 38" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/3ceb7f04-99b3-4f88-9887-001c424a9499">
<img width="1440" alt="Screenshot 2023-09-29 at 07 42 03" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/c56a4ff5-0edb-43f4-ab3d-f0b4a1943642">
