### ISSUE TITLE
Allianz - cred ca ar trebui sa existe si varianta Allianz- Tiriac

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#16]
Exista site-ul https://www.allianztiriac.ro/ro_RO/cariere.html care are 2 sectiuni separate.

Locuri de munca Alianz-Tiriac si Allianz Group.

Alianz-Tiriac are inclusiv propriul logo.

**Comment by TheMrM** [comment]
Scraperu-ul culege joburile din platforma internationala "https://careers.allianz.com/"
Ar trebuie facut inca unul pentru a culege joburile si din platforma "https://www.allianztiriac.ro/ro_RO/cariere/cariere-posturi-disponibile.html"
