### ISSUE TITLE
BASTICO has no active jobs in Romania and on the ejobs website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#160]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    1. Open URL in the browser
    2. Go to "BASTICO" Company 
    3. Open the "BASTICO" website and eJobs website
    4. Check the valid jobs in Romania

EXPECTED RESULTS:
Bastico has the job "Cargo Survey" active in Romania, location Constanta

ACTUAL RESULTS:
Bastico has no active jobs in Romania

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/63356322-b4db-414c-9a8e-45fd0112767b)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/abf45d31-0c99-4f4d-b69c-34013a98528c)

**Comment by TheMrM** [comment]
Removed the expired job. The company should automatically delete.

**Comment by lalalaurentiu** [comment]
This company is no longer on the peviitor website!
