### ISSUE TITLE
EXPIRED JOB - Kokka Flokka Studios 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#161]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

   1. Open URL in the browser
   2. Go to "Kokka Flokka Studios" Company 
   3. Open the "Kokka Flokka Studios" website and eJobs website
   4. Check the "Coafor 100% (m/f) - Switzerland € 3'700- € 5'000.- / Mo" validity 

EXPECTED RESULTS:
 The job "Coafor 100% (m/f) - Switzerland € 3'700- € 5'000.- / Mo" is valid

ACTUAL RESULTS:
The job "Coafor 100% (m/f) - Switzerland € 3'700- € 5'000.- / Mo" is expired

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/581d46e4-53fe-4335-8c46-e73ef08a9177)

**Comment by TheMrM** [comment]
Removed the expired job. The company should automatically delete.

**Comment by lalalaurentiu** [comment]
This post is no longer on the peviitor website!
