### ISSUE TITLE
 EXPIRED JOB- MLG EUROPEAN BUILDING TRADE SRL  - Montator fatade ventilate, tamplarie pvc

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#162]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to "MLG EUROPEAN BUILDING TRADE SRL" Company
  4.  Open the "MLG EUROPEAN BUILDING TRADE SRL" website and eJobs website
  5. Check the validity of the "MLG EUROPEAN BUILDING TRADE SRL" job

EXPECTED RESULTS:
The job "Montator fatade ventilate, tamplarie PVC"  is valid

ACTUAL RESULTS:
The job "Montator fatade ventilate, tamplarie PVC" is expired

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/18ad558b-3a31-4786-891d-c9f33cebc8a0)

**Comment by TheMrM** [comment]
Removed the expired job. The company should automatically delete.

**Comment by lalalaurentiu** [comment]
This post is no longer on the peviitor website!
