### ISSUE TITLE
EXPIRED JOB - OMNICONVERT - UI/UX Team Lead

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#163]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to "OMNICONVERT" Company
  4.  Open the "OMNICONVERT" website 
  5. Check the validity of the "UI/UX Team Lead" job

EXPECTED RESULTS:
The job "UI/UX Team Lead"  is valid

ACTUAL RESULTS:
The job "UI/UX Team Lead" is not on the list of open jobs

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/7b92e811-f737-4567-8ae1-7f50d0c41515)

**Comment by TheMrM** [comment]
Scraper dose not extract the jobs correctly.

**Comment by lalalaurentiu** [comment]
@TheMrM fix it!!!
