### ISSUE TITLE
NO CITY - Tickbird - Frontend Developer

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#164]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to "Tickbird - Frontend Developer" and check the location - city
  4. Open the "Tickbird" website 
  5. Check the job location
 

EXPECTED RESULTS:
 The job has a location/city or is it remote as on the Tickbird website

ACTUAL RESULTS:
The job does not have a location

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f00a4f02-1c81-4e51-9c92-e507203b9b73)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a531fde2-b2f7-48d5-8953-49bd2bf6e127)

**Comment by TheMrM** [comment]
Scraper dose not extract the jobs correctly.

**Comment by lalalaurentiu** [comment]
<img width="1440" alt="Screenshot 2023-10-01 at 22 46 51" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/93b1a9fb-a00c-4fba-8035-6eb5584b9976">

This post have remote object no need to specificate city
