### ISSUE TITLE
NO CITY -  Tickbird -  Functional Safety Engineer    

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#165]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to "Tickbird - Functional Safety Engineer  " and check the location - city
  4. Open the "Tickbird" website 
  5. Check the job location
 

EXPECTED RESULTS:
 The job has a location/city or is it remote as on the Tickbird website

ACTUAL RESULTS:
The job does not have a location/city

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/19aa643c-9a87-44d6-86de-02aa6a7e3add)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/0d8ba273-f510-467d-9b6c-92dc0dee556b)

**Comment by TheMrM** [comment]
Scraper dose not extract the jobs correctly.

**Comment by AdrianaCionca** [comment]
The scraper runs correctly and the job has a location
