### ISSUE TITLE
KBR - KBR.PY

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#166]
ENVIROMENT: production
URL: https://dev.laurentiumarian.ro/scraper/based_scraper_py/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open API URL in browser
2) Type {"file": "KBR.py"} in "Content:" box
3) Click on the button "Post"
4) Check the result ( take a screenshot)
5) Open the careers section of the company website : https://careers.kbr.com/us/en/search-results?keywords=&p=ChIJw3aJlSb_sUARlLEEqJJP74Q&location=Romania
6) Check the number of jobs available for Romania
7) Compare it with the number of jobs from the API URL

EXPECTED RESULTS:
The number of jobs returned by the API URL for KBR should be the same like the number of jobs posted on the company website on the careers section .

ACTUAL RESULTS:
The number of jobs RETURNED by the API  URL for KBR is void,  the number of jobs posted on the company website on the careers section for Romania is 3.
![Screenshot (313)](https://github.com/peviitor-ro/based_scraper_py/assets/35573782/ee050b54-3589-4c79-a2f8-4b303bd8a36e)
![Screenshot (314)](https://github.com/peviitor-ro/based_scraper_py/assets/35573782/d57af596-d08c-462b-8d31-5bbffdbb0ca4)

**Comment by lalalaurentiu** [comment]
Fixed!
