### ISSUE TITLE
Different job country (Romania instead of Bulgaria) - Tremend - Security Architect

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#168]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in the browser
  2. Go to "Tremend - Security Architect " and check the location - country
  3. Open the "Tremend" website 
  4. Check if the location on the "Tremend" website is the same as the location on https://solr.peviitor.ro

EXPECTED RESULTS:
The country is the same on https://solr.peviitor.ro and on the Tremend website

ACTUAL RESULTS:
The country is Romania on  https://solr.peviitor.ro and Bulgaria on the Tremend website

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/b3060bb9-b92f-4602-8a1f-4ba99a4c7813)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/63b3880f-8ce3-4460-ae1c-52e9834681d9)

**Comment by TheMrM** [comment]
Scraper dose not extract the jobs correctly.
