### ISSUE TITLE
BAT - logo putin diferit de cel de pe site-ul lor

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#17]
https://careers.bat.com/search-jobs/Romania/1045/2/798549/46/25/100/2

**Comment by TheMrM** [comment]
Este diferit deoarece la noi pe site e incarcat sub forma de " .png"  : https://firme.peviitor.ro/assets/bat.png
Cel de pe site-ul official este incarcat sub forma de " .svg" : https://cdn.radancy.eu/company/1045/v2_0/img/temporary/shared/bat-logo.svg
