### ISSUE TITLE
ING pe viitor sunt 235 de locuri de munca iar pe site-ul ING sunt 212

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#18]
Tocmai de aceea unele joburi returneaza 404.

Si mai este o problema. Cand faci post  { "file": "ing.js" } de pe https://dev.laurentiumarian.ro/scraper/based_scraper_js/

Primesti acest rezultat:

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "succes": [
        ""
    ],
    "status": "active",
    "jobs": 1
}

Nici aici nu functioneaza ok sau fac eu ceva gresit.

**Comment by lalalaurentiu** [comment]
Reparat!
