### ISSUE TITLE
WTB - Pe site-ul lor sunt 2 sectiuni de cariere

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#19]
WTB - Pe site-ul lor sunt 2 sectiuni de cariere, pe una sunt 6 posturi iar pe alta 10 posturi.

https://www.wtb.ro/careers/
https://www.wtb.ro/category/careers/

Nu am inteles foarte bine de unde sunt preluate posturile fiindca link-ul care se deschide din peviitor.ro nu coincide cu niciuna dintre variante. peviitor.ro sunt 8 posturi.

https://www.wtb.ro/candidati-posizioni/inginier-software/

**Comment by TheMrM** [comment]
Joburile sunt luate de pe  "https://www.wtb.ro/wp-admin/admin-ajax.php"

**Comment by TheMrM** [comment]
URL pe care il foloseste screaper-ul este  :  " https://www.wtb.ro/wp-admin/admin-ajax.php "
Iar daca verificam " /sitemap.xml " gasim acele 8 joburi postate : " https://www.wtb.ro/wp-sitemap-posts-candidati-posizioni-1.xml "

**Comment by TheMrM** [comment]
On firmepeviiotr.ro  if we search for the company jobs are duplicated ! Same job appears twice!

**Comment by lalalaurentiu** [comment]
Fixed by @TheMrM
