### ISSUE TITLE
Inetum -  Inetum Careers button does not open company website

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#191]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/inetum/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on the 'Inetum Careers' button
3)  Check the new tab opened by the' Inetum Careers" button

EXPECTED RESULTS:
Inetum company  website opens in a new tab

ACTUAL RESULTS:
URL: https://scrapers.peviitor.ro/src/inetum/index.html# opens in the new tab

**Comment by lalalaurentiu** [comment]
it is normal to open in a new tab
