### ISSUE TITLE
Veeam - 'Vezi postul' button does not open the job, it opens the apply section

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#192]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/veeam/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2)Go to 'English Teacher' job
3) Click on the 'Vezi postul' button
4)Check the new tab opened by the 'Vezi postul' button

EXPECTED RESULTS:
The 'English Teacher' job opens in the new tab

ACTUAL RESULTS:
The apply section opens in the new tab

**NOTE: The bug also reproduces for the following jobs**:
         -  Vendor Support Engineer (Japanese Speaker)
         - Public Cloud Data Protection Engineer
         - Virtualization Backup Engineer (French Speaker)
         - Veeam Backup for Cloud & Service Providers Engineer
         - Veeam Backup for Databases Engineer
         - Virtualization Backup Engineer
         - Veeam Backup for Linux Engineer
         - Virtualization Backup Engineer (German Speaker)
![BUG-01](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/551d9e0b-4c40-4396-8dd3-e5b32fd848e1)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After fixing, the bug is reproduced for the following jobs:

- Public Cloud Data Protection Engineer -Bucuresti
- Virtualization Backup Engineer (French Speaker) -Bucuresti
- Veeam Backup for Databases Engineer -Bucuresti
- Virtualization Backup Engineer (German Speaker) - Bucuresti
- Veeam Backup for Linux Engineer -Bucuresti
- Virtualization Backup Engineer (Weekend shifts) -Bucuresti

**Comment by lalalaurentiu** [comment]
- Public Cloud Data Protection Engineer -Bucuresti not available
- Virtualization Backup Engineer (French Speaker) -Bucuresti not available
- Veeam Backup for Databases Engineer -Bucuresti not available
- Virtualization Backup Engineer (German Speaker) - Bucuresti not available
- Veeam Backup for Linux Engineer -Bucuresti not available
- Virtualization Backup Engineer (Weekend shifts) -Bucuresti not available
