### ISSUE TITLE
Nextgh - Network Engineer - different job location

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#200]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/nextgh/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Check job location for Network Engineer on scrapers.peviitor.ro/src/nextgh/index.html
3) Click on the 'Vezi postul' button under Network Engineer job
4) Check job location for Network Engineer 

EXPECTED RESULTS:
Job location for Network Engineer is Satu Mare

ACTUAL RESULTS:
Job location for Network Engineer is Cluj-Napoca

**Note**: The bug also reproduce for:
-  Fullstack developer
- Database Developer
- Hardware Design Engineer (Mid-Senior level)
- Mobile developer with Flutter
- Cloud Infrastructure Engineer

![Capture 3](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/074d1282-e469-4b61-9469-7a37f4cee275)

![Capture 4](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/167887f4-283a-452a-a9ff-12bd48122bdf)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the location of the jobs is displayed correctly
