### ISSUE TITLE
Arabesque - 'Arabesque Carrers' button does not show jobs in Romania

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#201]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/arabesque/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check jobs available
4) Click on 'Arabesque Carrers' button
5) Check jobs available

EXPECTED RESULTS:
'Arabesque Carrers' button shows jobs in Romania

ACTUAL RESULTS:
Arabesques Carrers button shows international jobs

![Capture 5](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/ea8189bf-9323-4ab9-8e2c-3e4a6aa81256)
![Capture 6](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6ec55901-908f-4dd9-b4c1-22fe09abd531)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting  Arabesque Carrers show jobs correctly
