### ISSUE TITLE
Veeam - 'Run Scraper' button does not load available jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#202]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/veeam/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check  available jobs

EXPECTED RESULTS:
'Run scraper' button load available jobs

ACTUAL RESULTS:
'Run scraper' button does not load available jobs, "No data in Local Storage" displayed on screen.

![BUG-02](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/1e2c0034-d269-49ea-ab94-cefabb4338f9)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
closed #202
