### ISSUE TITLE
Missing job type -Inetum- Architect 

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#206]
![Bug Inetum missing job type - Architect            2023-10-23](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/9febfa11-5562-4b14-b51e-adf508b5413c)
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2.  Type 'Inetum' company in the search bar
3. Click on the button "Cauta"
4.  Open link https://www.inetum.com/en/job/lead-architect-iam-mf
5.  Check the job type 

EXPECTED RESULTS:
The job should be on-site, hybrid or remote 

ACTUAL RESULTS:
There is no job type specified

**Comment by lalalaurentiu** [comment]
the job type is not present in the job description, and the job type is not required if it is not present
