### ISSUE TITLE
Inetum job type missing - data analyst 

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#207]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type 'Inetum' company in the search bar
4. Open link https://www.inetum.com/en/job/data-quality-specialist-iam-mf
5. Check the job type
![Bug Inetum missing job type data analyst](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/2c114849-e221-4bdc-8e16-b5bce404799c)

EXPECTED RESULTS:
The job should be on-site, hybrid or remote

ACTUAL RESULTS:
There is no job type specified

**Comment by emese85** [comment]
@lalalaurentiu please tell me if this issue is correctly done

**Comment by lalalaurentiu** [comment]
Fixed!
