### ISSUE TITLE
Inetum job type missing - Full Stack Java Developer M/F (Middle-Senior)

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#209]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open link https://www.inetum.com/en/job/full-stack-java-developer-mf-middle-senior
2. Check the job type

EXPECTED RESULTS:
The job should be on-site, hybrid or remote

ACTUAL RESULTS:
There is no job type specified

![Screenshot 2023-10-23 220307](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/1410b24d-9722-4b87-8376-83728f93a9d6)

**Comment by lalalaurentiu** [comment]
the job type is not present in the job description, and the job type is not required if it is not present
