### ISSUE TITLE
Inetum job type missing - Security Analyst 

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#210]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open link https://www.inetum.com/en/job/security-analyst-mf
2. Check the job type

EXPECTED RESULTS:
The job should be on-site, hybrid or remote

ACTUAL RESULTS:
There is no job type specified
![Screenshot 2023-10-23 221106](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/126c1d8d-541b-4267-aca2-2ccfe1097c3c)

**Comment by lalalaurentiu** [comment]
Fixed!
