### ISSUE TITLE
Bancatransilvania - The location of all jobs is missing

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#211]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/bancatransilvania/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3)Check the location of any job

EXPECTED RESULTS:
All jobs have the job location displayed

ACTUAL RESULTS:
The location of the jobs is not displayed
![Capture 7](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/45ec824b-0f08-4f77-89e9-8c724b178c1a)
![Capture 8](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/1d91790d-f3a6-494f-b4af-15170e6a1b1c)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the location of the jobs is visible. Fixed.
