### ISSUE TITLE
Vodafone - 'Run Scraper' button does not load available jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#212]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/vodafone/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check section 'Status'

EXPECTED RESULTS:
Run Scraper button load available jobs

ACTUAL RESULTS:
Status 'Api Error' is displayed on the screen

![Capture 9](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6839f2cd-5ddc-4700-b179-44308db3d3ed)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
Retested.
