### ISSUE TITLE
Siemens Healthineers - The number of jobs posted is different on scrapers.peviitor.ro than the jobs posted on the company website

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#213]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/siemenshealthineers/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on "Run Scraper" button
3) Check  Jobs available
4) Click on 'Siemens Healthineers Careers' button
5) Check Jobs available on Siemens website

EXPECTED RESULTS:
The number of jobs posted on https://scrapers.peviitor.ro/src/siemenshealthineers/index.html is the same as the number of jobs posted on company website

ACTUAL RESULTS:
The number of jobs posted on https://scrapers.peviitor.ro/src/siemenshealthineers/index.html is different than the number of jobs posted on company website
![Cap 10](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/dd0ad873-b032-4571-b756-fa9be1b466b6)
![Cap 11](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/084e50a9-b493-4534-9d53-f9a68374395b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
Retested
