### ISSUE TITLE
Generali - The number of jobs posted is different on scrapers.peviitor.ro than the jobs posted on the company website

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#214]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/generali/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on "Run Scraper" button
3) Check Jobs available
4) Click on 'Generali Careers' button
5) Check Jobs available on Generali website

EXPECTED RESULTS:
The number of jobs posted on https://scrapers.peviitor.ro/src/generali/index.html is the same like  the number of jobs posted on the company website.

ACTUAL RESULTS:
The number of jobs posted on https://scrapers.peviitor.ro/src/generali/index.html (0) is different than the number of jobs posted on company website (6)
![Cap 12](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/24f86af0-b5f9-4ab9-9a2d-b677d9166ba3)
![Cap 13](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/2f5ff5f1-c4f9-4e9a-811d-3037d47c7523)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the number of jobs on https://scrapers.peviitor.ro/src/generali/index.html) is the same as the number of jobs on company website.
