### ISSUE TITLE
Wtb -'Controlor calitate' job is missing on https://scrapers.peviitor.ro/src/wtb/index.html 

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#215]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/wtb/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Go to wtb logo and click on wtb careers
4) Check for 'Controlor calitate' job on the www.wtb.ro/category/careers/
5) Check jobs loaded by the 'Run Scraper' button 

EXPECTED RESULTS:
'Controlor calitate ' job  is found between the jobs loaded by the 'Run Scraper' button

ACTUAL RESULTS:
'Controlor calitate ' job is missing from the jobs loaded by the 'Run Scraper' button.
Instead a job is found('RESPONSABIL SSM, SU SI MEDIU') that does not appear on https://www.wtb.ro/category/careers/

![cap 16](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6a0ce8b6-04db-4e5e-87f2-bf1c34f4cf81)
![cap17](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/7136f75d-3752-4946-99f0-ab728b262c2f)

**Comment by lalalaurentiu** [comment]
Jobul este prezent doar ca intr-o alta pagina.
<img width="1440" alt="Screenshot 2023-11-16 at 15 08 55" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/4441862b-64da-4945-b45b-9da6c2f07144">

**Comment by AdiVanca** [comment]
After retest the number of jobs is the same on scrapers.peviitor.ro as the number of jobs on company website
