### ISSUE TITLE
KWS - The location of the jobs is not recognized by scraper as an existing city

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#216]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/kws/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check location for the jobs loaded by the 'Run Scraper' button
4) Go to KWS logo and click on KWS Careers 
5) Check location for the jobs on company website

EXPECTED RESULTS:
The location of the jobs is recognized by the scraper as an existing city

ACTUAL RESULTS:
Scraper displays that Bucuresti and Braila are not cities in Romania
![cap18](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/69e2e9fe-a2bd-48b2-b731-096e2ba160e2)
![cap19](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/2443bfbd-86bb-4cde-8923-84f1401633a2)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the location of the jobs is recognized as an existing city
