### ISSUE TITLE
Enel - Scraper status inactiv

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#217]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/enel/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check scraper Status

EXPECTED RESULTS:
Scraper Status is Activ

ACTUAL RESULTS:
Scraper Status Inactiv

![cap15](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/8dbbf6d8-fd62-47e2-8808-f0b4803b77fd)

**Comment by lalalaurentiu** [comment]
Scraperul este inactiv deoarece nu sunt joburi disponibile.
<img width="1440" alt="Screenshot 2023-11-16 at 15 53 51" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/23bae371-3f9d-4055-bb66-66f134faa647">
