### ISSUE TITLE
BetFair - Incorrect Location in the Jobs Section and mismatch of listed job numbers

### ISSUE THREAD

**Issue by AndreeaPopa9** [peviitor-ro/based_scraper_py#220]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/betfair/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:
1) Open URL in browser
2) Navigate to the jobs section where the location name "Napoca, Romania is not a city in Romania" is displayed
3) Then check the number of jobs displayed on this page
4) Click on "Careers" button to enter the company's website
5) Check the number of job listings on the company's website
6) Compare it with the number of jobs from the URL

EXPECTED RESULTS:
The correct location name is displayed: Cluj-Napoca, Romania.
The number of jobs posted on the URL matches the number of jobs posted on the company's website.

ACTUAL RESULTS:
The location is displayed incorrectly: "Napoca, Romania is not a city in Romania".
The number of jobs posted on the URL (68) doesn't match the number of jobs posted on the company's website (69).

<img width="787" alt="Screenshot 2023-11-01 115835" src="https://github.com/peviitor-ro/based_scraper_py/assets/129062169/47c00f0d-333d-4db2-890f-954cfbbac48c">

<img width="331" alt="Screenshot 2023-11-01 105922" src="https://github.com/peviitor-ro/based_scraper_py/assets/129062169/894eacee-300b-4d94-8848-4d54323de48d">

<img width="851" alt="Screenshot 2023-11-01 112552" src="https://github.com/peviitor-ro/based_scraper_py/assets/129062169/296f05e2-0017-4640-81db-9818080beb17">

**Comment by lalalaurentiu** [comment]
Fixed!
