### ISSUE TITLE
MSD - missing job type for Campaign and Data System job 

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#223]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/  
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.  Open the URL   https://jobs.msd.com/gb/en/job/R261532  in the browser
2. Look for job type 

EXPECTED RESULTS:
A job type should appear 

ACTUAL RESULTS:
No job type appears 

![Screenshot 2023-11-06 173148](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/4c8fafc3-9c2c-4ff4-9e87-3dee42726f1c)

**Comment by lalalaurentiu** [comment]
the job type is not present in the job description, and the job type is not required if it is not present
