### ISSUE TITLE
MSD- Missing job type for Vaccines Communications Manager

### ISSUE THREAD

**Issue by egeto-emese-qa-tester** [peviitor-ro/based_scraper_py#224]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL   https://jobs.msd.com/gb/en/job/R263038  in the browser
2. Look for job type

EXPECTED RESULTS:
A job type should appear

ACTUAL RESULTS:
No job type appears (on-site, remote/hybrid)

![Screenshot 2023-11-06 175605](https://github.com/peviitor-ro/based_scraper_py/assets/120163768/eff2a767-f64c-4a1a-a322-d63f86291de8)

**Comment by lalalaurentiu** [comment]
the job type is not present in the job description, and the job type is not required if it is not present
