### ISSUE TITLE
pe VEEAM sunt listate comopanii internationale

### ISSUE THREAD

**Issue by davidmondoc** [peviitor-ro/based_scraper_py#227]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/veeam/index.html
Browser: Chrome
Device: laptop
OS: MacOS 14 Sonoma

STEPS TO REPRODUCE:
1) Opne URL in browser
2) Run Scraper
3) scroll and find first listed jobs
4) check if jobs listen internationally are remote jobs

EXPECTED RESULTS:
there should be jobs listed in Romania only

ACTUAL RESULTS:
There are jobs listed internationally also. 

![Screenshot 2023-11-07 at 12 24 37 PM](https://github.com/peviitor-ro/based_scraper_py/assets/61200936/f874bafe-dd58-45a8-be40-e4388b4f0eea)

**Comment by lalalaurentiu** [comment]
Scraperele pot Adaugă ,în baza de date, joburi din toată lumea.
