### ISSUE TITLE
BCR-The message "Timis is not a city in Romania" is displayed

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#228]
ENVIROMENT: production
URL:  https://scrapers.peviitor.ro/src/bcr
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Run scraper for BCR company 
3. Check the location for the "Partner clienti Retail_Timisoara"

EXPECTED RESULTS:
The correct name of the location that should be displayed is Timisoara, as on the company's website.

ACTUAL RESULTS:
The message "Timis is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/ba3d68f7-3747-468d-b1a7-9e9cbbe02485)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting. Working as expected

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/19bba289-a4e2-4522-b15d-a5c86411b4db)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/2a8ddaf3-acce-4892-8bde-1810cbd0ea95)
