### ISSUE TITLE
BCR-The message " Prahova is not a city in Romania" is displayed 

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#231]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/bcr
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2.Run scraper for BCR company
3.Check the location for the "Specialist Contact Center"

EXPECTED RESULTS:
The location of the job should be a locality, not a county

ACTUAL RESULTS:
The message "Prahova is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/987a5eeb-b954-45de-b0a9-e06b05dca2c6)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting. Working as expected

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/7afe341e-7a02-49e6-a960-68f0f4d4e446)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/f8e10705-a42c-486d-916d-1e51b07051da)
