### ISSUE TITLE
Msgsystems - The message "Cluj-Napoca , Tg. Mures, Timisoara is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#234]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Msgsystems" Company
3. Check the job locations
4. Open scrapers.peviitor.ro
5. Check the job locations

EXPECTED RESULTS:
The city of the jobs is: Cluj-Napoca , Tg. Mures, Timisoara
    

ACTUAL RESULTS:
On solr.peviitor.ro the city of the jobs is: ["Cluj-Napoca , Tg. Mures, Timisoara"] 
On the scrapers.peviitor.ro the message "Cluj-Napoca , Tg. Mures, Timisoara is not a city in Romania" is displayed 
Only one job out of the 12, "Accounts Receivable Specialist" has a single location, Cluj-Napoca, which is correct

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f7844289-5bee-48c0-bf1b-728ab312a684)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/01065894-6ce6-499a-a40a-3b3dd33b4a2b)

**Comment by lalalaurentiu** [comment]
fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the cities of the jobs are: Cluj-Napoca, Tg. Mures, Timisoara
