### ISSUE TITLE
Lseg - The number of jobs on solr.peviitor.ro(126) is not the same as the number of jobs on Scrapers.peviitor.ro(132), The message "2 or 3 Locations is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#235]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Lseg" Company
3. Check the number and locations of the jobs
4. Open scrapers.peviitor.ro and run scraper for "Lseg" Company
5. Check the number and locations of the jobs

EXPECTED RESULTS:
The number of jobs on solr.peviitor.ro is the same as the number of jobs on scrapers.peviitor.ro
The city of all the jobs is "Bucuresti"
    

ACTUAL RESULTS:
The number of jobs on solr.peviitor.ro(126) is not the same as the number of jobs on Scrapers.peviitor.ro(132)

The messages: 
   "2 Locations is not a city in Romania" is displayed for 14 jobs
   "3 Locations is not a city in Romania" is displayed for 1 job
   "Bucharest - Iuliu Maniu Boulevard is not a city in Romania" is displayed for 1 job

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a43f41df-f323-453e-b85d-bb4a0185eda4)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/421ca2af-fe3f-43ed-ada5-40884a711ba7)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/296356f3-e607-40ff-aeb2-529d210662fe)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a358c832-c1f1-443a-af28-47111526800c)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/48c4539a-2122-40ee-82a0-84c73e696667)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the number of jobs on solr.peviitor.ro is the same as the number of jobs on scrapers.peviitor.ro
The city of all the jobs is "Bucuresti"
