### ISSUE TITLE
Eon - On solr.peviitor.ro the city of the job is: ["Remote (pe teritoriul României"]

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#236]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Eon" Company
3. Check the city for the "Consultant IT SAP Module FI-CA & BI-IN" job 
4. Open scrapers.peviitor.ro and run scraper for "Eon" Company
5. Check the location for the "Consultant IT SAP Module FI-CA & BI-IN" job 

EXPECTED RESULTS:
The job "Consultant IT SAP Module FI-CA & BI-IN" is remote as on the company website
    

ACTUAL RESULTS:
On solr.peviitor.ro the city of the job is: ["Remote (pe teritoriul României"]
On the scrapers.peviitor.ro the message "Remote (pe teritoriul României is not a city in Romania" is displayed 

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/4c301e34-a1df-4990-872b-03a37f7a1586)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/33889476-9acb-4dd9-849a-e01e32859732)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/d703cd33-847c-41c9-a40e-e797556bf866)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The Scrapers UI does not recognize "Piatra-Neamt" as a city


![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/d19b7955-fd88-48a9-a894-1f3ea0eb07ba)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/1ecb0fc2-205c-4676-a614-021fd800f02a)

**Comment by lalalaurentiu** [comment]
Fixed!
