### ISSUE TITLE
Linde - The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#238]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Linde" Company
3. Check the location of the jobs

EXPECTED RESULTS:
Jobs have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the following jobs:
   - Reliability TAR & Productivity Expert - Region Europe East (m/f/d) 
   - Regional Procurement Category Manager - Region Europe East (m/f/d) 
   - Senior Manager PGP Production, Technology and Innovation - Region Europe East (m/f/d) 

 The message "Timisoara, Timis is not a city in Romania" is displayed on scrapers.peviitor.ro for the job: "Procurement Expert Supply Chain Due Diligence (m/f/d)"

On the company website, the location of the jobs is Romania, no city is specified

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/079a4fab-e43c-4713-9483-904bdd31089b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.

**Comment by AdrianaCionca** [comment]
After retesting on solr.peviitor.ro the job "Data Analytics Expert (m/f/d)" is located in "Lisboa" instead of Timisoara as on the company's website.
The job "Senior Manager PGP Production, Technology and Innovation - Region Europe East (m/f/d)" is displayed on the company website but is missing from solr.peviitor.ro.


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/1d0e4c45-4ed3-4f5a-b165-12c0359ea6b7)



![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/2db56843-388e-4079-a9a8-3c245b29bf54)




![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/47a9aa61-8f7a-44ef-8c0d-06f41555232d)



![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/3e2b9d80-213a-43ba-b54c-f10357778fe3)
