### ISSUE TITLE
Penny - Incomplete location for the job "Inspector Siguranta Alimentului" 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#239]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Linde" Company
3. Check the location for the jobs:  "Inspector Siguranta Alimentului" and "Casier - Bucuresti (sector 6)"
4. Open https://cariere.penny.ro/joburi
5. Check the location of the jobs

EXPECTED RESULTS:
The locations for the job "Inspector Siguranta Alimentului" are  "BACAU, FILIASI, STEFANESTII DE JOS, TURDA" as on the company's website 
The location for the job "Casier - Bucuresti (sector 6)" is "Bucuresti"

ACTUAL RESULTS:
The location for the job "Inspector Siguranta Alimentului" is "Bacau"
  
 The message "BUCURESTI SECTOR 6 is not a city in Romania" is displayed on scrapers.peviitor.ro for the job "Casier - Bucuresti (sector 6)"

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/515e0323-1c96-4344-b446-8d2842ea9303)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/3a826ca0-a9f1-47e7-ab71-c4eb318d7ae5)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/078531d2-2d2d-49f4-8a4c-06230ddb609b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, all job locations are correct
