### ISSUE TITLE
Selgros - the scraper doesn't import all the cities place allocated to jobs

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#241]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Selgros" Company
3. Check the location for the job "Lucrător comercial raion Pește"
4. Open the link https://selgros.mingle.ro/ro/embed/apply
5. Check the scraper imports all the cities place assigned to the jobs

EXPECTED RESULTS:
For example, the locations for the job "Lucrător comercial raion Pește" are: Iasi, Targu Mures, Constanta, Brasov, Bucuresti - Pantelimon, Bucuresti - Drumul Taberei, Bucuresti - Baneasa", as on the company's website

ACTUAL RESULTS:
The location for the job "Lucrător comercial raion Pește" is only Iasi

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/cd3667ce-f227-42d4-815f-fa996682db73)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/8f9c3713-37c9-477f-a7b9-e8b3408b003a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/72aba619-7150-4ce8-9401-828fc79500f3)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting.

On the https://scrapers.peviitor.ro/ problem can be considered solved.

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/9eda6b8a-63f7-4c7e-80ea-572cda101621)
