### ISSUE TITLE
Intel - The city of jobs is "Romania" on solr.peviitor.ro  instead of "Bucharest, Timisoara, Cluj-Napoca and/or Galati"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#249]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Intel" Company
3. Check the city of the jobs
4. Open https://jobs.intel.com/en/job
5. Check the job locations

EXPECTED RESULTS:
The job location is "Bucharest, Timisoara, Cluj-Napoca and/or Galati" as on the company's website

ACTUAL RESULTS:
The job location is "Romania"
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/61853c6d-809c-4f41-ae3f-c3746209adf3)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/bd591c9b-3bdd-4cf3-8942-eef25a03a880)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/53dc8432-f988-4ff9-a60a-1ae8361675f5)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the locations of the jobs are "Bucharest, Timisoara, Cluj-Napoca and/or Galati" as on the company's website
