### ISSUE TITLE
Autonom - Incomplete location for the jobs: "Agent Servicii Client" and "Consultant Servicii Client"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#250]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Autonom" Company
3. Check the location for the jobs: "Agent Servicii Client" and "Consultant Servicii Client"
4. Open https://www.autonom.ro/cariere
5. Check the location of the jobs

EXPECTED RESULTS:
The locations for the job "Agent Servicii Client" are "Focșani, Iași, Bacău" 
The location for the job "Consultant Servicii Client" is "Satu Mare, Oradea" as on the company's website 

ACTUAL RESULTS:
The location for the job "Agent Servicii Client" is "Focsani"
The location for the job "Consultant Servicii Client" is "Satu Mare"

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/0d21ff9f-58d0-4b51-b0db-653bd8dc8021)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/19a50606-0ad5-406b-8203-8b4eab5b9e90)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/1659d7b2-0e34-4960-bd57-dbff8d6a06c1)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/37ddd36c-4497-4b73-bb88-66bf6fbb3022)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting:
- The locations for the job "Agent Servicii Client" are "Focșani, Iași, Bacău"
- The location for the job "Consultant Servicii Client" is "Satu Mare, Oradea" as on the company's website
