### ISSUE TITLE
Allianz - The message "Romania is not a city in Romania" is displayed for all 120 active jobs on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#256]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Allianz" Company
3. Check the location of the jobs
4. Open https://careers.allianz.com
5. Check the location of the jobs

EXPECTED RESULTS:
Jobs have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed for all 120 active jobs on scrapers.peviitor.ro
54 jobs have "Bucharest" as their location
66 jobs have only "RO" as their location and hybrid work system

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/6442a515-e79b-4dfc-8897-bda3d93c5b9a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/283081ab-911f-42c9-9305-82bc1612732a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, all the jobs have a city as a location
