### ISSUE TITLE
Bat - For 2 of the 58 jobs displayed on scrapers.peviitor.ro, the location is Romania instead of Croatia

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#257]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Bat" Company
3. Check the location of the jobs
4. Open https://careers.bat.com
5.  Check the location of the jobs

EXPECTED RESULTS:
Jobs located in Croatia should not be displayed

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the following jobs: 
- Production Technician in Croatia 
- Operator in Croatia 
For these 2 jobs, the location is Romania instead of Croatia 

The problem is in the database of the Bat company because under the job title "Romania" is written even though the job location is Croatia.

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f9b8e6d7-06bb-4417-8465-26f4cd8ac8ad)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/af0a19e6-9838-4050-a422-4049aac6bbeb)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/e23aed6d-38b2-4b69-bc49-aa12fb1f9004)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/2161060d-9e90-4564-a4e8-563b46eb6744)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/5011d1db-1f78-498c-bee5-adb31ee03e17)

**Comment by lalalaurentiu** [comment]
Fixed!
