### ISSUE TITLE
Fortech- update active jobs on the scrapers.pe vitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#259]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Fortech" Company
3.Open https://www.fortech.ro/careers-fortech
4.Check the "active jobs"
5.Check the active jobs on the scrapers.pe vitor.ro 

EXPECTED RESULTS:
The active jobs on the companie's site are 11

ACTUAL RESULTS:
The active number of jobs on the scrapers.pe vitor.ro are 20

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/8e1a462f-bbee-40af-82c0-686b3af9f69a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/3e0e9d2e-8879-4a7b-beab-ab0d0ee93fd2)

**Comment by davidmondoc** [comment]
### mie imi apar 20 si pe peviitor.ro

![Screenshot 2023-11-13 at 3 48 50 PM](https://github.com/peviitor-ro/based_scraper_py/assets/61200936/cb61cf43-180a-43ba-bb6b-72626c182e5a)

![Screenshot 2023-11-13 at 3 49 21 PM](https://github.com/peviitor-ro/based_scraper_py/assets/61200936/b13561f2-83e3-48c5-a6ef-33982b276e9e)
