### ISSUE TITLE
Capgemini - The job city for 5 jobs out of 62 jobs is "Any Romania base" on solr.peviitor.ro instead of "Iasi, Cluj-Napoca, Bucuresti, Suceava and/or Brasov"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#260]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Capgemini" Company
3. Filter query:  city: "Any Romania base"
4. Open https://www.capgemini.com
5. Check the location of the jobs for which a response was received after performing the query filter

EXPECTED RESULTS:
The job location is one of the Capgemini bases from Romania: "Iasi, Cluj-Napoca, Bucuresti, Suceava and/or Brasov" as on the company's website

ACTUAL RESULTS:
The job city for 5 jobs out of 62 is "Any Romania base" on solr.peviitor.ro instead of Iasi, Cluj-Napoca, Bucuresti, Suceava and/or Brasov"
On the scrapers.peviitor.ro the message "Any Romania base is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/9786e3bd-b9c1-4298-86cd-c942f41479bc)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/53c6e9f7-7756-408a-bb4d-4a78903c2069)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/855b7099-faa4-4042-8536-eed7ac98eedd)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/2dcc6188-b100-477c-9847-f67b1f343bd8)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, all the jobs have a city as location
