### ISSUE TITLE
Fortech- The active jobs on https://scrapers.peviitor.ro/ are (20) and on the company's site rest active (9)

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#261]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Fortech" Company
3.Open https://www.fortech.ro/job-openings/
4.Check the numbers of active jobs

EXPECTED RESULTS: 
The numbers of the jobs on the company's website are 20 (11 inactive) and 9 active : "PL/SQL Developer"; " Accountants"; "Data Engineer"; " Software Architect"; "Chromium Developer "; " Salesforce Client Executive"; "DevOps Engineers "; " Front-End Developers"; " Python Developers".

ACTUAL RESULTS:
The numbers of active jobs on the scrapers.peviitor.ro are 20

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/4fcf6782-acfe-41e2-904e-4082708c7d38)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/663762d5-966e-4786-b26a-caca455e5632)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e6277e19-a0d0-477d-a1f6-f9bfb31db7d4)

**Comment by lalalaurentiu** [comment]
jobs are present on their site and scraper doesn't know it's active or not
