### ISSUE TITLE
Samsung - The job locations is "Romania" instead of "Bucharest" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#263]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Samsung" Company
3. Check the jobs location
4. Open https://sec.wd3.myworkdayjobs.com/en-US/Samsung_Careers
5. Check the jobs location

EXPECTED RESULTS:
For all 6 active jobs, the location is "Bucharest"

ACTUAL RESULTS:
The job locations is "Romania" instead of "Bucharest" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/0cde9dc7-7688-41d1-bbb7-ea33d48b51a4)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a8da2e25-6233-4b06-abb7-bdd83058a87b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, for all 5 active jobs, the location is "Bucharest"
