### ISSUE TITLE
Siemensenergy - The job locations is "Romania" instead of "Bucharest or/and Prahova, Brazi" ; 5 jobs out of the 181 are not located in Romania

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#265]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Siemensenergy" Company
3. Check the job locations
4. Open https://jobs.siemens-energy.com
5. Check the job location 

EXPECTED RESULTS:
The job location is "Bucharest or/and Prahova, Brazi" as on the company's website
Only 176 jobs are located in Romania

ACTUAL RESULTS:
The job locations is "Romania" instead of "Bucharest or/and Prahova, Brazi"  
5 jobs out of the 181 are not located in Romania
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed
The following jobs are not located in Romania:

Financial Head (f/m/d) of Overhead Line Inspection (SIEAERO) 
[IT Assurance & Compliance Expert
(Ober) Monteur (w/m/d) im Außendienst 
Product Design Engineer (f/m/d) for Turbomachines 
Solution Architect (f/m/d) Manufacturing & Product Ops 

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/b42a4045-87da-4d31-9a22-d0fbb887a722)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/968060aa-619f-4cd9-b1a3-23c860a2bcfe)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f85f29d4-73bb-47c8-a9b9-a82d1970d871)

**Comment by AdrianaCionca** [comment]
After retesting, the job location is "Bucharest or/and Prahova, Brazi" as on the company's website

BUT

The number of jobs displayed on scrapers.peviitor.ro (175) is not the same as the number of jobs displayed on the company website (177)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/0e7156cd-c803-4b52-ac58-39dc9d14f0df)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/881970e3-1001-476f-8675-260d7d69408a)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a207fcbc-01e6-47dc-8cd0-125f0a69cfbe)

**Comment by lalalaurentiu** [comment]
Many of them are in another country and do not specify Romania only global
