### ISSUE TITLE
Thoughtworks - The jobs city is  "Bucuresti-Dorobanti" instead of "Bucharest" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#266]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Thoughtworks" Company
3. Check the job locations 
4. Open https://www.thoughtworks.com/careers/jobs
5. Check the job locations 
6. Open https://scrapers.peviitor.ro
7. Run scraper for "Thoughtworks" company and check the location of the jobs

EXPECTED RESULTS:
The jobs city is "Bucuresti" as on the company's website

ACTUAL RESULTS:
The city of the job is "Bucuresti-Dorobanti" instead of "Bucharest"  
On the scrapers.peviitor.ro the message "Bucuresti-Dorobanti is not a city in Romania" is displayed
The following jobs have "Bucuresti-Dorobanti" as city:
- Lead Data Engineer
- Senior Android Developer (RX knowledge)
- Senior Android Developer (SD UI experience) 
- Senior Infrastructure Developer (DevOps) 
- Senior iOS Developer 

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/2658c0fd-f377-4675-913f-325864d03c7b)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/c756497c-bf63-49d2-9628-95cf7729207c)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/83969d7d-db2a-43ef-afd9-231d539f52aa)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, all jobs have a city as location
