### ISSUE TITLE
Adi/Analog Devices - This employer isn't currently communicating about their brand in the Romanian community

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#268]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open URL in browser
2.Run scraper for "Adi" Company
3.Open the careers section of the company website https://www.analog.com/en/about-adi/careers.html

EXPECTED RESULTS:
The number of jobs returned by the API and the number of jobs posted on the company website in the career section is the same in both cases: 0

ACTUAL RESULTS:
The number of jobs posted on the company website on the careers section is only for Abroad
The scraper status is "Active"

**Comment by lalalaurentiu** [comment]
And why did you open issues?

**Comment by AdinaIT** [comment]
Because at that time the situation was as described in the current results

Retesting

Actual Results:
On https://scrapers.peviitor.ro  the status of jobs is maintained as active, and on the company's website there are 0 active jobs for Romania.

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/2f775ca4-a5ef-42c8-a4a3-4c917a6a2d8c)


![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/edf21341-6203-4ace-9a94-e04b0c65e2ea)
