### ISSUE TITLE
SGS - All the company's jobs from all over the world, not only from Romania are displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#269]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "SGS" Company
3. Check the number and the location of the jobs
4. Open https://www.sgs.com/en/careers-at-sgs/job-opportunities
5.  Check the number of valid jobs for Romania

EXPECTED RESULTS:
Only jobs located in Romania are displayed on scrapers.peviitor.ro
35 jobs are active in Romania

ACTUAL RESULTS:
All the company's jobs from all over the world, not only from Romania are displayed on scrapers.peviitor.ro (3886 jobs)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/ffab770a-4ef0-4e11-b5f3-fd32b4433ddc)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/cb5b2d8c-e9db-4ec5-ab30-2e822e8fa706)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/ff3d60c5-e3c0-4250-86eb-471fc431c5fa)

**Comment by lalalaurentiu** [comment]
Jobs from across the globe are welcomed by our search engine, and we've implemented filters specifically designed to identify positions based in Romania.
<img width="1440" alt="Screenshot 2023-11-27 at 13 00 33" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/01524e08-30d7-45d9-b0bd-4242c31dd9bd">
