### ISSUE TITLE
Heineken -The city of 2 jobs is "Ciuc" instead of "Miercurea Ciuc" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#270]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Heineken" Company
3. Filter query: city: "ciuc"
4. Open https://careers.theheinekencompany.com
5. Search for jobs by location "Miercurea Ciuc"

EXPECTED RESULTS:
The job location is "Miercurea-Ciuc"

ACTUAL RESULTS:
The "city" for 2 jobs is "Ciuc" instead of "Miercurea Ciuc" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Ciuc is not a city in Romania" is displayed
The following jobs have "Ciuc" as a city
- Process Engineer 
- Quality Specialist 

!! The job location on the company's website is incorrectly written as Ciuc instead of Miercurea Ciuc.

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/fe1f04a9-2f2e-4fac-904f-59b7643d4f97)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/31cde3af-e2c2-489e-9dd7-83b75a2e046c)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/17cd7e46-bd88-4f67-9ecc-ff27674ce942)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/3d5750f3-5a96-4576-9293-5eaeaaa03c97)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the job location for the job "Quality Specialist" is "Miercurea-Ciuc"
