### ISSUE TITLE
MegaImage - On the scrapers.peviitor.ro the message "Municipiul Bucuresti is not a city in Romania" is displayed

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#274]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Execute Query for "MegaImage" Company
3.Check the city of the jobs
4.Open https://cariere.mega-image.ro/joburi
5.Check the job locations

EXPECTED RESULTS:
The job location is "Municipiul Bucuresti " as on the company's website. 

ACTUAL RESULTS:
The job location is "Municipiul Bucuresti is not a city in Romania". 
On the scrapers.peviitor.ro the message "Municipiul Bucuresti is not a city in Romania" is displayed. 
The number of jobs with this type of location is 31

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/d18d9da2-e3f8-4a5f-9596-4ba7f9a3aa12)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/4f6f4fa0-f778-46c0-a0bf-8748bc099389)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/d9790cc3-f9b8-4857-9aad-5fd2b5cc974a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting. Issue resolved

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/084f4cb6-8c50-4d41-acbd-bcf135073d12)
