### ISSUE TITLE
Ericsson -  Incomplete location for 7 jobs out of the 23 jobs; The city of all  jobs is "Bucharest,Bucharest,Romania"  instead of "Bucharest" or "Bucharest and Timisoara"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#275]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Ericsson" Company
3. Check the job locations
4. Open https://jobs.ericsson.com/careers
5.  Check the job locations

EXPECTED RESULTS:
The location of the jobs is "Bucharest" or "Bucharest and Timisoara" as on the company's website

ACTUAL RESULTS:
The city of the jobs is "Bucharest, Bucharest, Romania" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Bucharest, Bucharest, Romania is not a city in Romania" is displayed

The following jobs are located in Bucharest and Timisoara:
- MS Automated Operations Engineer RAN and Spanish-  Bucharest,  Timisoara
- MS Automated Operations Engineer IP and Spanish
- Tax Manager
- Indirect Tax Comp. & Tech. Manager
- TX Integration Engineer
- RAN Technical Lead
- Mobile MS Telecom Field Specialist- Iasi - multiple locations (Bucuresti, Brasov, Constanta, Maramures, Suceava-Botosani, Galati)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/ac93bc52-75d7-44b4-9849-8575d9b5b7dd)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/b4e29bcf-734f-4b2a-ac11-9e6e6a27e4e7)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a4df9434-2e49-4676-bae1-0f2f01881f0a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/7588ef6c-e0d2-40a2-8004-3d96ac629627)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the location of the jobs is "Bucharest" or "Bucharest and Timisoara" as on the company's website
