### ISSUE TITLE
Bancatransilvania - Incomplete location for several jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#279]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/bancatransilvania/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check job location for the following jobs:
                  - Responsabil Tura- Centru de Procesare
                  - Manager Relatii Clienti Microbusiness/IMM
                  - Responsabil Regional - Administrare Numerar si Echipamente
                  - Analist Regional Agribusiness
4) Go to Bancatransilvania logo
5) Click on Careers
6) Check the location for the same jobs in the url that opened in step 5

EXPECTED RESULTS:
The location of the jobs loaded by the scraper is the same as the location of the jobs on the website (https://www.ejobs.ro/company/banca-transilvania/8092)

ACTUAL RESULTS:
The location of the jobs loaded by the scraper is incomplete as follows:
-  Responsabil Tura- Centru de Procesare - missing Targu Mures
- Manager Relatii Clienti Microbusiness/IMM - missing Targu Mures
- Responsabil Regional - Administrare Numerar si Echipamente - missing Cluj Napoca
- Analist Regional Agribusiness - missing Cluj Napoca

![cap08](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/a210c7d2-97be-4117-bda9-cf4edede9da4)

![cap09](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/71537d3e-a817-47c7-86ee-d9b36662dc42)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After Re-Test the location of the jobs is displayed correctly
