### ISSUE TITLE
TBIBank - The number of jobs posted on scrapers.peviitor.ro (0) is not the same as the number of jobs posted on the company's website (20)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#280]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "TBIBank " Company
3. Check the number of jobs
4. Open https://tbibank.ro/career
5. Check the number of jobs

EXPECTED RESULTS:
The number of jobs is the same on scrapers.peviitor.ro as on the company's website 

ACTUAL RESULTS:
 The number of jobs posted on scrapers.peviitor.ro (0) is not the same as the number of jobs on the company's website (20)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/1b20a8f5-3daf-4285-a2bc-f6bd00d4c2f2)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/8109bade-3968-4b65-816c-230da0567f2e)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/bcd39e47-09ed-4ec4-8995-22e16ead2614)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the number of jobs is the same on scrapers.peviitor.ro as on the company's website
