### ISSUE TITLE
Strabag -  The job location is "Romania" for all the jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#283]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Strabag " Company
3. Filter query city: "Romania"
4. Open https://jobboerse.strabag.at
5. Check the job locations

EXPECTED RESULTS:
The location of the jobs is a city in Romania or Bucharest
- 19 jobs are located in Bucharest
- 17 jobs are located in multiple locations

ACTUAL RESULTS:
The city of the jobs is "Romania" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/d5e00f31-bec8-4cc4-861d-658c3d9eee19)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/90ec3f8e-f3b0-472d-af9a-9d5d12689b2b)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/301e76e6-0682-41b2-87c8-2d54146c4bd5)

**Comment by lalalaurentiu** [comment]
Fixed!
