### ISSUE TITLE
Fedex - The city of the job "Operation Support Agent-Associate " is "Judetul Cluj" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#284]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Fedex" Company
3. Check the city for the job "Operation Support Agent-Associate"
4. Open https://careers.fedex.com/fedex/jobs
5. Check the locations for the job "Operation Support Agent-Associate"

EXPECTED RESULTS:
The location of the job is Apahida commune in Cluj county as on the company's website

ACTUAL RESULTS:
The city of the jobs is "Judetul Cluj" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Judetul Cluj is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/9f8b1a3d-397f-438f-a909-5f36fb91f64b)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/b317881a-459d-4b9e-91c4-6d5735435110)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/33ea6d83-3491-487d-8083-e5fd3f083425)

**Comment by davidmondoc** [comment]
@lalalaurentiu in API la orasa nu apare apahida. apahida apare doar in descrierea jobului.

**Comment by davidmondoc** [comment]
@AdrianaCionca te rog verifica daca apare Cluj Napoca. daca trebuie apahida, va trebui sa revenim asupra codului cu laurentiu

**Comment by AdrianaCionca** [comment]
@davidmondoc Apare doar Apahida care e comuna in Judetul Cluj.

**Comment by lalalaurentiu** [comment]
Fixed!
