### ISSUE TITLE
SonnentoR- The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#302]
ENVIROMENT: production
URL: https;//scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "SonnentoR" company
3. Chek the location for the job: " Business Development Manager"

EXPECTED RESULTS:
Job have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the job: "Business Development Manager"
On the company website, the location of the job is Reghin
Execute "q" on https://solr.peviitor.ro/solr & the city of job is Romania

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/8ca07221-1805-4246-b23b-26686f232f04)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/fbb2c1d3-9b25-47e2-b73c-4063384f6faa)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting:**
Run scraper.
Validating the bug fix

**Regression testing**:
On the https://scrapers.peviitor.ro/src/sonnentor, the changes did not introduce new problems and did not affect other functionalities.
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/810f58dd-2f4d-4985-91c8-7d851b275ad1)
