### ISSUE TITLE
Nextgh - Scraper takes on-site jobs from Malta

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#303]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/nextgh/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check jobs loaded by 'Run Scraper' button

EXPECTED RESULTS:
The scraper only loads jobs from Romania

ACTUAL RESULTS:
The scraper loads jobs from Romania and Malta

![cap10](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/807228a8-92a6-45de-9d6a-1ebb633160ee)

**Comment by lalalaurentiu** [comment]
Our search engine accepts jobs from all over the world.

**Comment by AdiVanca** [comment]
"Our search engine accepts jobs from all over the world."

On-site jobs from Malta should not exist in our search engine.
Only if  they are remote or hybrid.
