### ISSUE TITLE
Siemenshealthineers - The scraper does not specify what type of job it is (remote/hybrid/on-site)

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#304]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/siemenshealthineers/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check job types
4) Open one of the jobs by clicking on 'Vezi Postul' button
5) Check job type

EXPECTED RESULTS:
The scraper specifies the type of the job ( remote/hybrid/on-site) if this is specified on the company site

ACTUAL RESULTS:
The type of the job( remote/hybrid/on-site) is missing for all jobs

![cap11](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/25fcd623-3c35-45e2-b273-b320f1942544)
![cap12](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/5fc25ca1-4098-43dc-a673-ffdd9f5eb658)

**Comment by lalalaurentiu** [comment]
Fixed!
