### ISSUE TITLE
IntesaSanpaoloBank- the message "București/Arad is not a city in Romania" is displayed on the scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#305]
ENVIROMENT: Production
URL: https://peviitor.ro/
Browser: Chrome
Device: Lapotop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in Browser
2. Run scraper fot IntesaSanpaoloBank company
3. Check the location for the jobs

EXPECTED RESULTS:
The jobs must have allocated two locations: Bucharest and Arad

ACTUAL RESULTS:
The message  "București/Arad is not a city in Romania" is displayed on the scraperspeviitor.ro for the  following jobs:

"System Engineer Administrator helpdesk"; 
"System Engineer Developer";
On solr.peviitor.ro the location of this jobs is: ["București/Arad"]

The message "București/Arad/Alte orașe - full remote is not a city in Romania"  is displayed on the scraperspeviitor.ro for the  following job: "Information Security Officer"
On the company website, the location for this job has message "Alte orașe", but no other city is specified
On solr.peviitor.ro the location of this job is: ["București/Arad/Alte orașe - full remote"]

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e51b6f8e-3e22-45dd-abf3-9d24ffe43eb3)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/1f7a9f2c-456c-4332-b3ef-652544edba81)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/30f67559-2a45-42db-8c57-f6c9bb8f8607)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/cc6b88c3-9581-4478-b2dd-ebeeb4ff7735)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/db21180a-f664-41e3-8b42-04b792400301)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Run scraper for IntesaSanpaoloBank company
**Retesting:**
-Validating the bug fix

**Regression testing:**
-On the https://scrapers.peviitor.ro/src/intesasanpaolobank/, the changes did not introduce new problems and did not affect other functionalities.
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e68a0ca5-6ae3-4265-b08f-96fcf66f58df)![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/6fa61365-eb3c-4c93-aa6f-a67ea5a32ae3)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e0481f11-0636-42f5-a498-1dda47ea5140)
