### ISSUE TITLE
Nestle -  The scraper does not specify what type of job it is (remote/hybrid/on-site)

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#308]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/nestle/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check job types
4) Go to logo and click on Careers
5) Check job types

EXPECTED RESULTS:
The scraper specifies the type of the job ( remote/hybrid/on-site) if this is specified on the company site

ACTUAL RESULTS:
The type of the job( remote/hybrid/on-site) is missing for all jobs
![cap017](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/efecf590-1f0d-4ce5-bb8e-45615e25b6d1)
![cap018](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/e0fe4340-48a8-485a-98b9-18a298a02c09)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After Re-Test the type of the jobs is displayed correctly
