### ISSUE TITLE
8x8 -  The number of jobs posted on scrapers.peviitor.ro (0) is not the same as the number of jobs posted on the company's website(7)

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#310]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/8x8/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check the number of jobs
4) Go to logo an Click on 'Careers'
5) Click on 'View Current Jobs'
6) Type Romania in Search bar
7) Press Enter

EXPECTED RESULTS:
The number of jobs posted on the https://scrapers.peviitor.ro/src/8x8/index.html is the same like the number of jobs  posted on the company website.

ACTUAL RESULTS:
The number of jobs posted on the https://scrapers.peviitor.ro/src/8x8/index.html is 0 and the number of jobs posted on the company website is 7.

![cap019](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/0bdfdb6b-6b90-4b0c-9e4a-80a4f8c59b84)
![cap020](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/5a562d56-51c5-4a5a-ba59-19cd4debc55e)

**Comment by lalalaurentiu** [comment]
They don't have any available jobs anymore.
<img width="1440" alt="Screenshot 2023-12-01 at 11 44 51" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/7bf6d115-cb8f-48f9-a7f8-b7dfa723a2df">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest the number of jobs is the same on scrapers and on company website
