### ISSUE TITLE
Cargill - The message "Multiple Locations is not a city in Romania" is displayed for 4 jobs on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#318]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Cargill" Company
3. Check the location of the jobs
4. Open https://careers.cargill.com/en/search-jobs/Romania
5. Check the location of the jobs

EXPECTED RESULTS:
Jobs has Bucharest as the location:
- Coordinator, Global Communications 
- Master Data Specialist 
- ANH Data Technical Lead 
- Supply Chain Management Trainee - full-time, permanent position 

ACTUAL RESULTS:
The message "Multiple Locations is not a city in Romania" is displayed for 4 jobs on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/1f8c736c-06b0-4c8c-b04f-4c1d6cd32165)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/77105434-6077-4e68-83e2-f59aabb30241)

**Comment by lalalaurentiu** [comment]
Fixed!
