### ISSUE TITLE
 1and1 - "no job type" for all jobs instead of remote/ hybrid

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/based_scraper_py#319]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/1and1/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type the name of the company in the search bar
3) Check job type
 

EXPECTED RESULTS:
Job type is remote/hybrid according to https://www.1and1.ro/careers

ACTUAL RESULTS:
"no job type"  appear 
![Screenshot_17](https://github.com/peviitor-ro/based_scraper_py/assets/124587607/0042c97a-4ca0-4cc1-979e-177ac7c3a36b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by LarisaM16** [comment]
looks ok now!
