### ISSUE TITLE
ORACLE -The message "Romania is not a city in Romania" and others like  that are displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#321]
ENVIROMENT: production
URL: https;//scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "ORACLE" company
3.Chek the location : " Romania is not a city in Romania"; "READING is not a city in Romania"; "United States is not a city in Romania";
"LONDON is not a city in Romania"; "Mexico is not a city in Romania"; "BENGALURU is not a city in Romania"; "United Kingdom is not a city in Romania"; 

EXPECTED RESULTS:
The jobs must have their location displayed on the scrapers.peviitor.ro

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the (66) job
The message "READING is not a city in Romania" is displayed on scrapers.peviitor.ro for the (1) job
The message "United States is not a city in Romania" is displayed on scrapers.peviitor.ro for the (2) job
The message "LONDON is not a city in Romania" is displayed on scrapers.peviitor.ro for the (1) job
The message "Mexico is not a city in Romania" is displayed on scrapers.peviitor.ro for the (1) job
The message "BENGALURU is not a city in Romania" is displayed on scrapers.peviitor.ro for the (3) job
The message "United Kingdom is not a city in Romania" is displayed on scrapers.peviitor.ro for the (3) job

Execute "fq" on https://solr.peviitor.ro/solr 

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e01f4dc3-de2d-45bd-8046-18cea25ddce0)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/c8ce6f41-2424-405a-85cd-e49183ea535f)

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
