### ISSUE TITLE
Cartofisserie - The message "Arad, Cluj-Napoca, Deva, Timisoara, Targu-Mures is not a city in Romania " is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#328]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "CARTOFISSERIE" Company
3. Check the location of the jobs

EXPECTED RESULTS:
The location Arad, Cluj-Napoca, Deva, Timisoara, Targu-Mures must be assigned to the following job:
- LUCRATOR COMERCIAL / AJUTOR BUCATAR
and
The location: Bucuresti, Constanta, Craiova, Iasi, Sibiu must be assigned to the following job:
- LUCRATOR COMERCIAL / AJUTOR BUCATAR

ACTUAL RESULTS:

- The messages: "Arad, Cluj-Napoca, Deva, Timisoara, Targu-Mures is not a city in Romania " and "Bucuresti, Constanta, Craiova, Iasi, Sibiu is not a city in Romaniai" are displayed for 2 jobs on scrapers.peviitor.ro

- Invalid button "Vezi postul "

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/f4e408f4-05e9-4139-8c8f-26f13bf99e11)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/df94e4e2-e080-4d20-9b32-3f3f88fd06b4)

**Comment by lalalaurentiu** [comment]
Fixed by @TheMrM
