### ISSUE TITLE
Mazars - The message "No city" is displayed for 2 jobs on scrapers.peviitor.ro 

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#331]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Mazars" Company
3. Check the location of the jobs
4. Open https://www.mazarscareers.com/ro/apply/job-offers/
5. Check the location of the jobs

EXPECTED RESULTS:
Jobs must have a city as the location
-Juniors in Mazars
-Assistant Manager – Financial Services

ACTUAL RESULTS:
The message "No city" is displayed for 2 jobs on scrapers.peviitor.ro
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/0ed9f5a8-b892-4998-8fd1-c952f267779c) 
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/d7f10be4-22f0-4988-aba0-0f38a9c3438c)

**Comment by lalalaurentiu** [comment]
Fixed!
