### ISSUE TITLE
CAT -  The job location is "Romania" for all the jobs instead of "Bucuresti - Mogosoaia, Timisoara, Constanta, Piatra Neamt, Craiova and/or Cluj-Napoca"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#337]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "CAT" Company
3. Filter query city: "Romania"
4. Open https://www.bm-cat.com
5. Check the job locations

EXPECTED RESULTS:
The location of the jobs is:
- TEHNICIAN INTERVENTII UTILAJE CATERPILLAR - Bucuresti - Mogosoaia, Timisoara, Constanta, Piatra Neamt, Craiova.
- Tehnician Interventii Motoare si Generatoare CAT - Bucuresti - Mogosoaia, Cluj Napoca, Craiova.
- Corespondent Service - Bucuresti - Mogosoaia, Timisoara

And Mogosoaia for the following jobs:
- Inginer Electric Motoare Caterpillar - Mogosoaia
- Inginer Electromecanic Motoare Caterpillar
- Lucrator Depozit (Magazioner)
- Inginer Electric Motoare Caterpillar - Mogosoaia
- Inginer Electromecanic Motoare Caterpillar
- Lucrator Depozit (Magazioner)
- Ucenic
- Inginer Automatist
- Key Account Manager
- Inginer Proiect Aplicatii Fotovoltaice
- Specialist Produse Service
- Reprezentant Comercial Utilaje Caterpillar
- Operator facturare
- Contabil
- Contabil Senior
- Asistent Logistica Service
- Analist Financiar

ACTUAL RESULTS:
The city of the jobs is "Romania" on solr.peviitor.ro
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/4dc10789-9c7e-4869-a23d-70c32d1a2337)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/9022d9cf-f4fb-403e-a853-b4905e368481)

**Comment by lalalaurentiu** [comment]
Fixed!
