### ISSUE TITLE
Otpbank - Location displayed incorrectly for the job as "Relationship Manager Micro"

### ISSUE THREAD

**Issue by AndreeaPopa9** [peviitor-ro/based_scraper_py#339]
ENVIROMENT: Production
URL: https://scrapers.peviitor.ro/src/otpbank/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on Run Scraper
3) Go to the Jobs section 
4) Check the city for the job as "Relationship Manager Micro".

EXPECTED RESULTS:
The city is displayed correctly: Târgu Mureș.

ACTUAL RESULTS:
The city is displayed incorrectly: "Târgu Mureș is not a city in Romania".

<img width="263" alt="1" src="https://github.com/peviitor-ro/based_scraper_py/assets/129062169/0961830a-a34c-427d-818b-f454e539fa6b">

**Comment by lalalaurentiu** [comment]
Fixed!
