### ISSUE TITLE
MolsonCoors - The message "Milwaukee is not a city in Romania"  is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#343]
ENVIROMENT: production
URL: https;//scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for the " MolsonCoors" company
3. Chek the location for the jobs:  "Team Lead - Procure-to-Pay (Accounts Payable)"  and "Solution Designer"

EXPECTED RESULTS:
The location for the jobs, on the web's company, must be a city in Romania

ACTUAL RESULTS:
1. The message "Milwaukee is not a city in Romania" is displayed on scrapers.peviitor.ro for the 2 jobs:  "Team Lead - Procure-to-Pay (Accounts Payable)"  and "Solution Designer"

2. On scrapers.peviitor.ro the jobs: "Senior Analyst - Group Consolidation" has only Bucuresti city as the location. 
   On the website company's this position has also following location: Bucuresti, Brasov, Iasi, Timis

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/06c8ac8e-d012-4fe1-a452-2874075954ef)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/6ad5cd64-f2bd-4a4d-b524-b147d88d058e)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/0cb1a7b5-6a71-46d5-ba5f-1b86100a95a8)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting:**

- Run scraper. 

EXPECTED RESULTS:

- On the website's company the location for this job "Senior Analyst - Group Consolidation" is Timis too.

ACTUAL RESULTS:

- On scrapers.peviitor.ro the job "Senior Analyst - Group Consolidation" has only 3 location: Bucuresti, Brasov si Iasi.




![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/a3d4e203-2d8f-4ca5-8994-7b150d752c11)


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/ff2fcadd-773a-466f-91b9-866c084640f7)

**Comment by lalalaurentiu** [comment]
if you consider that bug has not been solved, please change the label from "Fixed" to "Bug", otherwise i consider it fixed
