### ISSUE TITLE
Parexel - The job location is "Bloemfontein, Czech Republic, Warsaw, Germany, Prague" for all the jobs instead of "Bucharest" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#345]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Parexel" Company
3. Check the job locations
4. https://jobs.parexel.com/en/search-jobs/Bucharest/Romania
5. Check the job locations

EXPECTED RESULTS:
The location of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
The city of all the jobs is "Bloemfontein, Czech Republic, Warsaw, Germany, Prague" on solr.peviitor.ro 

On the scrapers.peviitor.ro the message "Bloemfontein, Czech Republic, Warsaw, Germany or Prague is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f1b18fe7-c0e8-40c3-918b-75e9f947a25f)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/68df7099-ac83-435b-91bd-b348bd53d141)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/eb285807-494b-4cde-b421-9fad4a009842)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/25ede2fe-e2d4-4924-87be-ccbac873fc75)

**Comment by lalalaurentiu** [comment]
Fixed!
