### ISSUE TITLE
KBR - The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#349]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for " KBR" Company
3.Check the location for all the 5 jobs
4. Run scraper on https://careers.kbr.com/us/en
5. Check the location for all the jobs

EXPECTED RESULTS:
Jobs must have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the following jobs:

-LCV EUCOM Romania: Operations Coordinator
- LCV EUCOM Romania: Logistics Warehouseman
- LCV EUCOM Romania: Food Services, Lead
- LCV EUCOM Romania: Logistics Warehouse Foreman
- LCV EUCOM Romania: Sous Chef
On the company website, the location of the jobs hasn't a city specified. Mentioned only Romania
https://careers.kbr.com/us/en

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/30c53a2b-668f-494f-a494-d06b5e799e65)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/2106207c-7418-49ae-a28b-989c745ee7c3)

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.

**Comment by lalalaurentiu** [comment]
assign me when the[434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f) is merged
