### ISSUE TITLE
UPS - The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#350]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "UPS" Company
3.Check the location for the job
4. Run scraper on https://www.jobs-ups.com/search-jobs/Romania
5. Check the location for the job

EXPECTED RESULTS:
On the website company the location for this job is Bucharest 

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the following job:
- Curier / Sofer, Otopeni

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/bb4fb3f9-e88a-440c-ae5e-97396ca1ca92)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/b04dc249-13e7-4379-9c6f-db0b938ae9ad)

**Comment by lalalaurentiu** [comment]
the company has no more jobs available

**Comment by AdinaIT** [comment]
Retested

Confirmed that on  the company site has not exist available jobs
