### ISSUE TITLE
farmaciatei.py Job title format is wrong

### ISSUE THREAD

**Issue by TheMrM** [peviitor-ro/based_scraper_py#36]
** ENVIREMENT **

DEV: firme.peviitor.ro
LINK URL: https://firme.peviitor.ro/
BROWSER: Chrome Version 114

** STEPS TO REPRODUCE **

1)Open url in browser
2)Search for company farmaciatei
3)Click on company logo

** EXPECTED RESULTS **

The job title should be in simple format.
Ex:   Farmacist

** ACTUAL RESULTS **

The job title has symbols in it 

![wrongformat2](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/7ba5bc41-bd44-406b-9bf9-a7071fb2b1f8)
![wrongformat1](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/d70a7110-f563-4f10-8ba8-e9219cbde6de)
![wrongformat](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/10566513-93ed-4c8b-835e-8289fcfdcf94)

The job title has icons in it

![returnicon](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/4ccb781d-7517-46ad-ad6c-6f32ba865959)

**Comment by lalalaurentiu** [comment]
Fixed
