### ISSUE TITLE
Crowe - The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for all the jobs

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#361]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Run scraper for "Crowe" Company
3. Check the location of the jobs

EXPECTED RESULTS:
All the jobs must have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for all (16) jobs
On the company website, the locations for this jobs: "JUNIOR ACCOUNTING CONSULTANT - HIBRID" ; "SENIOR PAYROLL CONSULTANT – HIBRID" and  "JUNIOR LEGAL CONSULTANT - HIBRID" are București, Cluj-Napoca, Timișoara and for rest of all is Bucuresti

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/64666f62-fcb2-419b-911b-bbb2cd1b095a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/40c3269f-19d4-4747-bbec-f260cf3ab428)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/7e6ffbc1-b19f-4b58-bfa0-7fe9f4f01728)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/99bda870-4867-456a-ba10-bd774d8d0493)

**Comment by lalalaurentiu** [comment]
Fixed!
