### ISSUE TITLE
ElectronicArts -The location for all jobs is "Romania" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#384]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "ElectronicArts" Company
3. Check the job locations
4. Open https://ea.gr8people.com/jobs
5. Check the location of the jobs
6. https://scrapers.peviitor.ro/src/electronicarts/
7. Check the location of the jobs

EXPECTED RESULTS:
The job location is "Bucharest" as on the company's website

ACTUAL RESULTS:
The location for all jobs is "Romania" instead of "Bucharest" on solr.peviitor.ro
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a4a83286-6d05-4878-ab13-70d6588e3d1d)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/ba15f096-8355-4d8d-a758-2e0f87271c76)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the job location is "Bucuresti" or "remote" as on the company's website

![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/ee7bf75f-b282-4e7b-86f6-307dbcb1e84f)
