### ISSUE TITLE
SKILLD - The message "Romania is not a city in Romania" and others like this (14) is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#388]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "SKILLD" Company
3.Check the location for the jobs
4. Run scraper on https://www.ejobs.ro/user/locuri-de-munca
5. Check the location for the jobs

EXPECTED RESULTS:
1.On the www.ejobs.ro/user/locuri-de-munca the location for this job: "Marketing Assistant" is Bucharest
2.On the  www.ejobs.ro/user/locuri-de-munca the location for this job: "Credit Controller" is Oradea
3.On the  www.ejobs.ro/user/locuri-de-munca the location for this job "Contabil Sef" is Apahida, Cluj Napoca, Floresti, Gilau, Turda, Vlaha
4.On the  www.ejobs.ro/user/locuri-de-munca the location for this job: "Store Manager Craiova" is Craiova
5.On the  www.ejobs.ro/user/locuri-de-munca the location for this jobs:
- "Inginer Proiectant Instalatii Electrice (Curenti Tari)"
- "Inginer Proiectant Instalatii Electrice (Curenți Slabi)"
-" Embedded Software Developer"
- "Sales Representative"
- "Credit & Risk Controller"
- "Junior Chartering Officer"
  is Bucuresti

6.On the  www.ejobs.ro/user/locuri-de-munca the location for this job: "Director economic" is București, Corbeanca, Ilfov, Mogosoaia, Otopeni, Ploiesti
7.On the  www.ejobs.ro/user/locuri-de-munca the location for this job: "Responsabil Achizitii" is Bucuresti, Voluntari
8.On the  www.ejobs.ro/user/locuri-de-munca the location for this jobs: "Store Manager Bucuresti" and "Lucrator Comercial" is Bucuresti, Otopeni

ACTUAL RESULTS:
1.For the following job: "Marketing Assistant", the message: "Bucuresti is not a city in Romania, Ilfov is not a city in Romania" is displayed on scrapers.peviitor.ro 
2.For the following job: "Credit Controller", the message: "Oradea is not a city in Romania" is displayed on scrapers.peviitor.ro  
3..For the following job: "Contabil Sef", the message: "Cluj-Napoca is not a city in Romania, Turda is not a city in Romania, Floresti is not a city in Romania" is displayed on scrapers.peviitor.ro
4. For the following job: "Store Manager Craiova", the message: "Craiova is not a city in Romania" is displayed on scrapers.peviitor.ro
5.For the following jobs: 
- "Inginer Proiectant Instalatii Electrice (Curenti Tari)"
- "Inginer Proiectant Instalatii Electrice (Curenți Slabi)"
-" Embedded Software Developer"
- "Sales Representative"
- "Credit & Risk Controller"
- "Junior Chartering Officer"
the message "Bucuresti is not a city in Romania" is displayed on scrapers.peviitor.ro

6.For the following job: "Director economic" the message:  "Bucuresti is not a city in Romania, Ploiesti is not a city in Romania, Ilfov is not a city in Romania" is displayed on scrapers.peviitor.ro
7. For the following job: "Responsabil Achizitii" the message "Bucuresti is not a city in Romania, Voluntari is not a city in Romania" is displayed on scrapers.peviitor.ro
9. For the following jobs: "Store Manager Bucuresti" and "Lucrator Comercial" the message "Bucuresti is not a city in Romania", "Otopeni is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/2036e175-9f53-470b-8253-f5a2198cd0c6)

**Comment by lalalaurentiu** [comment]
Fixed!
