### ISSUE TITLE
SVN Romania - The job description are written with letters and characters

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#391]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "SVN Romania" company and check the job title

EXPECTED RESULTS:
The Job titles are written correctly

ACTUAL RESULTS:
The job title is written with letters and characters for 3 jobs: Junior Advisor, Senior Advisor and Reprezentant Vanzari Imobiliare

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/f6f3077d-ed36-4b29-ac09-5e0c06065949)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/b2d17974-4fd2-4e40-8166-b22e0c7e977b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the job title is written correctly as on the company's website



![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/810bd6f2-41c6-4c2c-85b3-c74aa2984e63)
