### ISSUE TITLE
Mcro - The job titles are not the same on scrapers.peviitor.ro as on the company website for 3 jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#392]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Mcro" Company
3. Check the job title for: ''React Native Engineer", "Automation QA" and "Project Manager "
4. Open the job on the company's website with the "Vezi postul" button and check the job title

EXPECTED RESULTS:
The job titles are "React Native - Mobile Engineer", "Automation QA Lead" and "Technical Project Manager" on  scrapers.peviitor.ro and on the company website

ACTUAL RESULTS:
The job title is not the same on scrapers.peviitor.ro as on the company website for 3 jobs

- React Native Engineer  instead of React Native - Mobile Engineer
- Automation QA instead of Automation QA Lead
- Project Manager - Technical Project Manager

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/aadcc584-f57d-4830-b48b-272363605467)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/42d09640-0313-4fe8-92eb-0cbb3f4524e5)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/e2b6696b-7ec0-4a67-b2af-b3310120015f)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/5b7adab6-8842-4047-b3c9-956616a35f7a)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/c76fa02d-c2da-4858-8705-729292ffa0d4)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/493ca59d-daa1-4b64-a9a0-ae0ea37e6213)

**Comment by lalalaurentiu** [comment]
That's the way they're displayed on their webpage.


https://github.com/peviitor-ro/based_scraper_py/assets/67306273/ce24ff6a-a8a4-4a86-8a49-bf904dac19cc
