### ISSUE TITLE
Synevo - The message "Laborator Central - Chiajna is not a city in Romania" is displayed on scrapers.peviitor.ro for the 3 jobs

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#393]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Synevo" Company
3.Check the location of the jobs

EXPECTED RESULTS:
Jobs should have a city as a location

ACTUAL RESULTS:
The message "Laborator Central - Chiajna is not a city in Romania" is displayed on scrapers.peviitor.ro for the following jobs:

-Registrator Medical dep. Anatomie Patologica
-Medic Anatomie Patologică
-Biolog/ Biochimist – departament Citogenetică

On the company website, the location of the jobs is Chiajna

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/8b232bd9-8321-4bd0-8b6c-4b9c3beb3c60)

**Comment by lalalaurentiu** [comment]
Fixed!
