### ISSUE TITLE
TBIBank -  The message "Sofia is not a city in Romania" is displayed on scrapers.peviitor.ro for (1) job

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#394]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "TBIBank" Company
3.Check the location of the jobs

EXPECTED RESULTS:
Jobs should have a city as a location

ACTUAL RESULTS:
The message "Sofia is not a city in Romania" is displayed on scrapers.peviitor.ro for the following job: 
-Executive Office Coordinator

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/e8b8f221-11ba-4d1b-85a8-80aa61afcc88)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting:**
Run scraper. The bug is no longer reproducible with the initial steps. Validating the bug fix

![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/539bd5ba-3d3a-40c2-89ed-0ec288475cf8)
