### ISSUE TITLE
Auchan - The message "Bucuresti is not a city in Romania" and others like this is displayed on scrapers.peviitor.ro for all the jobs

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#396]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Run scraper for "Auchan" Company
3.Check the location for all the jobs

EXPECTED RESULTS:
Jobs should have a city as a location

ACTUAL RESULTS:
The message "Bucuresti is not a city in Romania" and others like this is displayed on scrapers.peviitor.ro for all the jobs
On the company's website https://cariere.auchan.ro/auchan/jobs/, the location of the jobs is specified as being exactly the city from the message displayed on the scrapers.peviitor.ro 

For ex.: 
"Timișoara is not a city in Romania", the location is Timisoara; 
"București is not a city in Romania", the location is Bucuresti
"Iași is not a city in Romania", the location is Iasi 
and so on

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/38527b0f-9b7a-4621-bfa7-55d7336dac10)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/917902d6-5454-4255-9ba4-8e6473fac83d)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/efbad2d3-b965-4130-9bf5-3d46064bfbc2)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/fbf6a082-602a-4e5e-ad8b-9eab98fa0078)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdinaIT** [comment]
The scraper was retested and new bugs were found.

**1. The message "Ilfov is not a city in Romania**" is displayed on https://scrapers.peviitor.ro/src/auchan/ for this jobs 
- Inspector Calitate Depozit Logistic Stefanestii de Jos
- Specialist Exploatare
  
For this Job "Inspector Calitate Depozit Logistic Stefanestii de Jos"  the location on the Company's website is  Platforma logistica Stefanestii de Jos
https://cariere.auchan.ro/auchan/jobs/job-inspector-calitate-depozit-logistic-stefanestii-de-jos/

For this Job "Specialist Exploatare"  the location on the Company's website is Platforma Logistica https://cariere.auchan.ro/auchan/jobs/job-specialist-exploatare/


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/9f6e6f6d-2239-4f30-bad2-2998d9bc4532)


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/d53a35a9-6c8b-46be-8a39-98a1716695c9)

![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/a9ac42c1-a192-425c-bd5a-4da81b07f5b8)


**2. On the https://peviitor.ro/rezultate?q=auchan, this job " Asistent Vanzari JYSK Constanta Auchan Sud" appears belongs to the JYSK company,  which is located inside the Auchan store**



![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/3f5f89bb-65f2-4178-9f53-43531d13ecc8)

**Comment by lalalaurentiu** [comment]
That job is no longer available

**Comment by AdinaIT** [comment]
**Regression testing**:

On the https://scrapers.peviitor.ro/src/auchan/ the changes required to fix the bug did not introduce new problems and didn't affect other functionality.
