### ISSUE TITLE
Veeam

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#4]
Noi avem 47 de posturi libere iar pe siteul lor sunt 51 de locuri pentru Romania.

https://careers.veeam.com/vacancies

Din pacate site-ul lor nu arata numarul de posturi disponibile. Singura optiune este numararea posturilor.

**Comment by lalalaurentiu** [comment]
L-am verificat și ai dreptate nu aduce toate joburile. Am sa-l remediez și te anunt.

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Ale230992** [comment]
Hello! Bug-ul inca se reproduce; pe site-ul companiei se regasesc 51 joburi disponibile iar pe al nostru site sunt 47 joburi disponibile.

**Comment by TheMrM** [comment]
The scraper correctly extracts the jobs with "country": "Romania" which are 47. It does not show the jobs that have multiple locations in the "country" section. You can test it out on [API_Scraper](https://dev.laurentiumarian.ro/scraper/based_scraper_py/) and use the Ctrl + f option to sort the job listing by the following keywords [ country": "Romani  ] which will point out the 47 jobs.
![1](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/60cdd993-82ad-48a5-af77-c9cbd99f21c7)

**Comment by Ale230992** [comment]
Well, I've just checked and the API shows 47 jobs located in Romania, while Peviitor there are 46.
The issue opened here was for the number of jobs displayed on https://careers.veeam.com/vacancies (there are 51, I've counted them multiple times), a number of jobs located in Romania that isn't returned by the API and isn't displayed on Peviitor. 

![veeam peviitor reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/f4a117d9-e73e-44de-bebc-e9010d8979ce)

![veeam scraper](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/22b86027-1017-40a4-8395-c37adb11f977)

**Comment by TheMrM** [comment]
Scraper now correctly extracts posts for Romania

![1](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/0b1e00b3-0c89-410d-8394-fb0aa6c31169)
