### ISSUE TITLE
Ahk - The 4 jobs displayed on scrappers.peviitor are not shown on the official company page.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/based_scraper_py#404]
COMPANY : Ahk
URL : https://scrapers.peviitor.ro/src/ahk/index.html
Browser : Google Chrome
Device : Laptop
OS :  Windows 10 

Precondition : 
The site must be opened in browser.
Internet Conections.

Steps : 

1. Scroll down and search for "Run Scrapper" button.
2. Click "Run Scrapper".

Expected results : 

The page displays 4 jobs.

Actual results : 

The 4 jobs is diplayed but when you hit " Vezi Postul " it redirects you to cloud not to company site.

![Capture1](https://github.com/peviitor-ro/Scrapers-UI/assets/116546445/37dc4b9e-dc82-474e-89fc-ed9e283727f3)

![Capture2](https://github.com/peviitor-ro/Scrapers-UI/assets/116546445/b3392bf7-d97f-49c7-a676-0908e0cd06cf)

**Comment by andbaldean** [comment]
@lalalaurentiu

**Comment by lalalaurentiu** [comment]
Ask has removed from our scrapers and database

**Comment by andbaldean** [comment]
AHK has been removed.

![Capture1](https://github.com/peviitor-ro/based_scraper_py/assets/116546445/9cf04c54-3874-44a6-9e04-2ded308ab427)
