### ISSUE TITLE
Uipath- Missing job type (Remote) for several jobs 

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#425]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Run scrapers for 'Uipath' company
3) Open the careers section of the company website
4) Check job type for:  
                                    - Senior Software Engineer
                                    - Manager, Software Engineering (Document Understanding)
                                    - Automation Program Advisor
                                    - Technical Account Manager
                                    - Senior Frontend Engineer (Orchestrator)
                                    - Senior Frontend Engineer (Document Understanding)
                                    - Senior Software Engineer (Orchestrator)
                                    - Principal Software Engineer (Document Understanding)
                                    - Senior Software Engineer (Automation Cloud)

5) Compare it with the job type on scrapers.peviitor.ro

EXPECTED RESULTS:
Job type on scrapers.peviitor.ro is 'Remote' for the jobs listed in step 3  as it is on the company website

ACTUAL RESULTS:
All jobs on scrapers.peviitor.ro display "No job type' in job type section

![a13](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/5a43b5ab-0b14-4200-9e08-7df7490694a8)

![a14](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/9481085d-df75-4f42-85a5-6a8313528b59)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the job type is no longer missing
