### ISSUE TITLE
Fga - "Nu sunt poziții deschise în acest moment" is displayed instead of the job title

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_py#432]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Fga" Company
3. Check the jobs
4. Open https://www.fgaromania.ro/recrutare-specialist
5. Check the jobs

EXPECTED RESULTS:
No job is uploaded on ScrapersUI because there is no active job on the company website

ACTUAL RESULTS:
"Nu sunt poziții deschise în acest moment" is displayed instead of the job title on ScrapersUI
The number of jobs displayed in the "Jobs" section is 1 on both, Scrapers UI and peviitor.ro

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/2c792b69-cc6f-435e-869b-23ac524a7830)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/f7b7ab84-5b48-446b-ac7f-ad9389b3ed19)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/36a939a6-622b-426c-bae4-12b3376af4f4)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, all active jobs on the company website are also displayed in UI scrapers


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/644cf160-aa8f-4617-9f45-07cdda1f914d)
