### ISSUE TITLE
Veeam- 'Vezi postul' button for all international jobs give 404 error on click

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#455]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/veeam/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Click on  'Vezi postul' button for international jobs only

EXPECTED RESULTS:
The button opens the job from the company website

ACTUAL RESULTS:
An error appears on screen when clicking on 'Vezi postul' button for all international job

![a34](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6399e961-96ed-447f-bdc6-0ab7ecb5e5a8)

**Comment by lalalaurentiu** [comment]
fixed
