### ISSUE TITLE
Veeam- Change careers link from https://jobs.smartrecruiters.com/?company=Veeam2&keyword=romania in https://careers.veeam.com/vacancies

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#456]
No more jobs are listed on https://jobs.smartrecruiters.com/?company=Veeam2&keyword=romania  for company Veeam

![a36](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/b5ba0b0e-7853-446f-9d56-7690746e6ee6)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, careers link is correct
