### ISSUE TITLE
Adi - On scrapers.peviitor.ro the message "Cluj Napoca is not a city in Romania" is displayed. The scraper doesn't recognize "Cluj Napoca" as a city

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#458]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Adi" Company
3.Check the location for the jobs

EXPECTED RESULTS:
On the website company the location for all the jobs is Cluj Napoca

ACTUAL RESULTS:
The message "Cluj Napoca is not a city in Romania" is displayed on scrapers.peviitor.ro for the all the jobs
The scraper UI doesn't recognize "Cluj Napoca" as a city

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/71ac3fa9-94f6-4a89-9e0b-44ec1f27765b)

**Comment by lalalaurentiu** [comment]
Fixed
