### ISSUE TITLE
Nolimits invalid logo

### ISSUE THREAD

**Issue by TheMrM** [peviitor-ro/based_scraper_py#46]
** ENVIREMENT **

DEV: firme.peviitor.ro
LINK URL: https://firme.peviitor.ro/
BROWSER: Chrome Version 114

** STEPS TO REPRODUCE **

1)Open url in browser
2)Search for company nolimits

** EXPECTED RESULTS **

There should be a company logo

** ACTUAL RESULTS **

It shows "LOGO NOT FOUND!"

![invalidlogo](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/708ecd21-6c86-483a-84ba-a1ac261ee008)

#NOTE
Alternative link to use in scraper logoURL 
 
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBERERQQExERFxQYERcZFxkZERkXGhgYFxcZGRcaGhcaICwkGiAoIBcXJDUlKC0vMjIyGSI4PTgxPCwxMi8BCwsLDw4PHBERHDEpICAxMTEzMTEvMTEyLzExMTExMTExMS8xMTExMTExMTExMTExMTExLzExMTExMTExMTExMf/AABEIAIYA+gMBIgACEQEDEQH/xAAcAAEAAwEAAwEAAAAAAAAAAAAABQYHBAECAwj/xABLEAABAwIDBQMHBgoJBAMAAAABAAIDBBEFEiEGBxMxQVFhcRQiMoGhsbMVIzVydJEzNkJSYoKEssHRFzRUc4OSlMPiJkPw8SWjtP/EABkBAQADAQEAAAAAAAAAAAAAAAABAgMEBf/EACsRAAICAgICAQMEAQUAAAAAAAABAhEDIRIxBEFRYYGhEyKR0eEzUnGxwf/aAAwDAQACEQMRAD8Au20e0D43mGKwIHnOtexI5BVw4rUXvxn38T7l9MajcKqRp1JebevUe8K34Xs9DGwZ2Ne6wJLhmF+4HQLweGfycskpUkz3+Xj+Lhi5RtyX8lWp9pKpn/czDsc0H2ix9qnKHa9p0lYW/pNOYfdzHtU8/DICLGGM/qD+SjqvZimkuWtLD+idPuOi6V4/k49xlf0ZyPyPEyalBx+qJOlrYphmY9rh3H3jouoKi1OzdTA7PC8ut+acrvu6rpw/aiSM8OpYdPyrWI+s3+S2h5bi+OWNP59GM/DUlywy5L49/wAFyRc9LVslbnY4OHcV0LuTUlaOJpp0+z2ReF5UkBERAEREAREQBERAEREAREQBERAEREAREQBERAEREBS9q6XhzxVFvNJaHeLDf2j3K4MNwCuTFKNtRC6I9Roexw5Fcuz9QXQ8N+j4jkcOunI+sWXJjxrHll8S39zpyZHkwx+Y6+z6JheURdZzHhcFfhkMws9gPfbUeBXcipKEZKpK0TGcou4umUuowSppHcWme5zeretuwjk5SWE7Rxynhy+ZJe2ugJ7j0PcVYlD4vgMVQL2yP6OA19Y6rkeCeN8sT18Pr7HYs8Mq45lv5Xf3+SYC8BVCnxCooXCKoDnx38141IHcevgdVaaaoZK0PY4OaRoQt8WZT1012n2YZcEob7T6a6OlERbmIREQBERAEREAREQBERAEREAREQBERAEREAREQHhcjKNgldKL5nNDXa6EDkSO1daKGkyU6CLixGvhpoXTzPayNtszjyGYho5d5AXJRbRUc8L6iOoidExxa9+bK1rgAbEut0I+9Sotq0iCXRUufedhDHZPKHO1tdsL3N++2qsOD41TVsfFp5WSN5GxsQexzTqPWpeOSVtNIi0SiIo7FsYpqRmeonjjb0zOsT4DmfUoSbdIk6ainZI0se0OaRqCLqsT4fNQvMtOS+K/nx3uQP8AzrzXP/SfhBdl8od48CS37qs+G4nBVR8SCaORnaxwNj2EfknuKzzeK3Ummmuma4s8oWu0+0+j70dQJY2SAWDmB3eLhUPB94jqjFfkw0zWjjTR8Tikn5oSG+S3XJ29VoLWACwGiwLZH8Z/22r/AHZl1ePCMoS5baX5MZPeuj9BIiLEkjMfrzTUk9S1ocYoZJACbAljSbH7lUt323UuKzSxvgjjEcYcC1xcTd1raq54jJEyGR8oBibG9zwRmBYBd1x10vooLZPF8KqXSeQsiDmNbnywcI2JNrmwvqCtI1wdq38/BHstKLgxXEYqWF9RM7LGwAudlLrAkDkNeZCjKDa/D54H1TJ2iKN+V7ngsAda9vOGp16KijJq0tEliXhZ9Ub28LY8taKl4v6TYgGnwzOB9iteA7QUtfHxaaQPANnC2VzT2OadQplimlbTRFol0VOxveNhlI8xuldI8ek2Juex7C64bf1r54JvKw2rkEQfJE9xs3isDQ49gcCR99lP6U6unQtF1VC3h7by4TJCyOGOQSMe45nFtshA0t4q+BVna3FsMpTEa9sRLw/h5oOJ6OXPbQ29JqjHXJWr+gfRJbOYk6ro4KpzQ10kTXloNwCegKiNqNuqPDJWQztmL3xh4yMa4Zbkcy4a3BU7h00Jp45Yg0QmFr4w1uUZC3M2zemh5LBN6ePU2IVUU1NJnY2nDHHI5tnZ3m3nAdCFphxfqTarQbpH6GjkDmhw5EA+or3VHpt5uEtYxpqHXDGg/Myc7eCsuCY3T10PHp3l8ectvlLfOFrixHeFnPHKO2mkLRKIq9j22FBQebUTtD7XEbQXPt4Dl67Kus3u4WTYtqQO0xNt7Hk+xTHFOStJi0aGig8F2noq6/k1Qx7gLlurXgdpYbG2o15KcVGnHTRJ5REQFO3r/Q1X/g//AKIllGwux9RikTgZzHSMmOYA3LpMrL2Zyvly6n+a1bev9DVf+D8eNQu4z6Om+2u+FCuvHNxwNru/6KtWz7u3R4Zkyg1Adb0+KCb9trW9iz7Zh82EY82lLyWmobA/oHskIEbiP12OX6EWCbZD/qhn2ujv/lhTBklPlGTtUGkjYNq8cjw+kkqn65RZjb+m86Nb9/PuBX5+ayrxioknmlaGsGaWWQ5YomX0A7OwNGp+8rSd+srhTUrB6Jne4+LGWH77lnVaTHg9I1noy1c7pe98QjbG0+Ac4271r42NKCku26Ik9nScNww0zW+VtB8ukZxuEcxjEEZBMN7hnELhf/0uWGaswSqjljkaQ5oe1zHZop4z7x07QewqsK0F5kwTz7/NYiGxHsbJE58jB3XY13ie9dcoOOm7T7sg/Quz+LR1tNFVR+i9l7XuWu5Oae8EELEtkvxn/bav92ZXfchK44dK0nRtW8N7gY4yR95v61SNkfxo/bav92ZcWOCi8kfhEt3R+gkReFwlyJ2o+j6z7HN8Nyy7cL+Frf7uH3yLUdqPo+s+xzfDcsu3C/ha3+7h98i6cX+jP7FX2i97z/oer+oz4jFk+77Yt2KNc+SYspo5bOY03Lnlo5X0GltdStY3n/Q9X9RnxGKt7iv6nU/aR8Nitjm4YJNd2GrZMv3Y4QYzGKdwNvT4r81+3U29lljsWH1VPiMuFwTOY+SYwFwcWh7C7TNblcWOngv0wsFxAf8AVY+3w+5inx8k5crd6vYkkXjBd1OHQxjjh88lvOJc5jQf0WNPvJVM3p7FQYeyKppmuax8hY9hcXAOylzC0nXk12nct1Wcb8B/8ZH9sZ8OVUw5pvIrfYaVFj3f4k+qwulmkN3mMscSdSY3Flz3nLf1qhb/ADnQftH+yrbuj+h6f603xnqpb/OdB+0f7KtiSXkV9WH0aJsjGHYXRNPI0EAPgYmLFN6eA02H1cUVNHkY6nDyM7nXdneL3eT0AW3bG/RlD9ig+ExZLvz/AK/B9kb8SRPGk1mavWxLovlPuzwhzGONM65Y0n5+XmR9dS3kEGE4fUGljLWRxSzBpc593tYTzcSfyQpyj/BM+o33JUwNlY6J4BY9jmuHa1wsR9xXPLJKTqTbRNGD7tsChxaqqJqxzpCxrXlpeQZHyF1ySNbC3IdoWqT7v8Je3IaKIac2lzXf5gbrMcS2BxXDZzPQOkkaL5XxutIG/mvZ19VwV7R7yMapCG1ULXdvFp3RuPrFvcuycZTd45a+LoqqXZftmtgYsNrnVUErjG6B8ZjeLlpL43Ahw5jzDz18VeFS9itvYMTJiLDHO1uYsLswcOpaetuxXRcWTkn+/ssqPZERVJKdvX+hqv8AwfjxKE3GfR03213wolbNssHfX0EtGx7WPkyWc4EgZJGP1t3MXDu92YkwumkgfKyQvnMgLQQACxjba9fMWynH9FxvdkVstiwTbP8AGhn2qi/dhW+LNsd2AnqcXbiTZomxiaB+Qh2a0QjBHZrkKePNQk3J+mGrJreTs+7EKB8cYvLG4SRj85zQQW+sE+uyw/A8TiZFJQ1jHmnfIH3aPnIJQLcRoPPTRzTzHgv08qPtXu5pK9xlaTDMdXPYAQ89r2dT3iy0wZ4xXGXXz8ESje0Y/wDINCDnOLU/Dv0hlMhHZwstr+uy+GNYiycRUVJFI2CNxEbSLySyPsHveB+UbAADkNFdRuYnza1kOS/PhOvbwv8AxV42T3f0eHOEovLPb8I8DzfqN/J8dT3rpn5OOO+Vv0Qos7dgsBOH4fFA4DiG75Prv5j1Cw9SyHZqoZHtI6R72sYKyrJc5waBpMNSdBzX6DWTYlugM88s/luXiSvfl4F7Z3l1r5+9cuHJG5c3XIlrqjR/l6i/tlL/AKiP+afL1F/bKX/UR/zWYf0Kn+3j/T/80/oVP9v/APo/5p+nh/3fgW/g0XH6iOXDauSN7HsNJPZzXBwNo3jQjRZruG/C1v8Adw++RX/Btl/JsLdhvFzZopWZ8lrcXPrlv0z9vRcWwWxPyS6d3lHF4rYx+DyWyF/eb+kqxlGOOUb7eg07TOnef9EVf1GfEYq1uK/qdT9pHw2K87T4R5dSS0mfJxGtGbLmtZwdyuOxRuweynyVBJFxuLxJc9+Hkt5oFrXPYojOKwuPuya3ZalgeIfjWPt8PujW+LP6nd5nxYYp5Tb59kvD4X5gAtnzd3YmCajyv2g1Zf1nG/D6Mj+2M+HKtHVa242Y+VKZlPxuFlnbJmyZ72a4WtcfnexUxSUZqT6Qe0R+6P6Hp/rS/Feqnv8AOdB+0f7K0XZHAvk+jjpOJxMhec2XLfO8u5XPaonb7Yr5W4Hz/C4XE/7efNxOH3i1uH7VrDJFZ+berZDTqiZ2N+jKH7FB8JqyjfrA4VdNLbzXU5aPFjyT8QLYsGovJ6aCnzZuFDHHmta+Robe3S9lH7VbNQYlBwZbgg5mPb6THdo7R2jqq4sijk5PrZLVo++z2Kw1NLFOx7S10TL+cLtdbVp7CDovtiGLRQ081TfOyFj3PyEOPmC5HisndudqWuIZXRZL88jw63e0G3tV92b2NZS4dJh0kplZIZM7g3IbSAAgans5qZwxrale+q9EJsk8D2ko65gfTzscbatvleO4sOoXfXthMbuOI+HlObPbLbre+iyrEdzZDs1LWW10EjDcfrs/kvhHukrpCBPiDMl+hkkNvB9gp4Ym7UqX/Gxb+CE2Eha/aEGlHzDZ53NIvYRWkDfUQWD1hfoJVvZTZGmwuMtiBdI62eR1szrdO4dwViuqZ5rJL9vSJitHuiIsiTgxWZ0cEj22zBjiO6w5+rmvGFzSPja57QLsaQQ697jU2sLLoqYBIx0Z5OaQfAiy+GH0z4m5HSB4AAb5mUgDt116LNp80/VFk48a92dT3WFzyChDj7cvEDW5LX/CDPbtyfwvdTb23FjyKiosKfGAxk1mDQAxtcQOwO/mFXJztcei2PjT5dks11wCOxcdfXcLK0NLnvdla29rm1ySegAXcBouCuohNlIcWuY67XAXsbWIIPMEK8r467Kxrlvo+tNLI4nPGG6CxD8wPsC6XFctNHI25kkDuWgjDQPafeuohFfH+yJVeivUmJStgMroy9rHSFzi8AloeeQ62A625KeieHta4ciAR4FcMeGgQPgzGzg/W3LOSeXrXZDGGMaz81oHjYWVMcZKlJ+vyaZJRk24qt/g+OJVnBidJlJsW6XsTdwH8VzsxB4kZE+PLxM2Q5w7VovY6aaeK6cQpRNGY72u5pva/ouDv4LxPRh8kUl7cMu07czcqSU7tPWv+9kRcapre/8AB2KOnry2ThMZmdkzG7soaL2FzY6lSKjqigc6TjMflfkym7cwIvcXFxqFafLXErGvZ70Nbxc7S0tcx2Vzb31tcEHqCF3ErhoaPhZyXFz3uu51ra2sAB0AC7iEjy477EqvXRGYHK58Ic52Y55Bfro9wHsXdUTNjY6R3otaSfAC6+OH0ghjEd72c43tb0nF38V9Z4WvY5jvRcC0+BFkipKKXuvyJOLk2ur/AARhxR7WNlfFljcW65wXNDjYFzbd45FTCiPktzmtjdKXRtLbN4YDiGm4DnX15DoFLtKiHPfL6Ez46o4a2t4bmRtbme8uyi9hYC5JPQL1o61z5XwvYGuaxrtHZgQSR2DsXzxWAnJK0SZ2khpYGkgOGtwdCNF8cLp5eLJK/P5zGNbmyhxtcnRvIa+Kzcp869X9qLqMODfuvvdk1dcFHUZ5J2Xd5j2jW1hdgOmnvXfZcdNSCOSWS5PEc0+Fmhv8FrJO1X3MotU779HaoJ+OjznNa0taTzkDXOtzLW+69rqdUQzCnR3EcoawkkNcwOy3NzlNxp43UZOWuJfHx3yJKCYPY145OaCPAi658RrhCwOLSbuDedgCepPQd66ImWaASTYDXQX79F86yBz22a/KfqhwI7CD0Uy5cddlU1y30fKiq3yXu1gFtC2QPB9gXco2hw0RPdKXAucADZoa2w62HXvUkkLr93YnxvR7IiLQqEREAREQBERAEREAREQBERAEREAREQBERAeqzDH8ExHDKh+J4fJLNG92aeB7nPJHaL6uA6dR3haeimMnF/KIasq+yW2VLiTPmzklA8+Jx84dpH547x67K0LP9r93rKh/llE/yerac12ksa93abeg7vHPr2qNwDeJLTS+RYvE6KVthxcuhHQvA6fpN07uq1eOMlyh/HsXXZqiL4U1QyVgkje17HC7XNcHNI7QRzX3WJIREQHhVbaKqfQzx1xc40z8sNS0klsYLvm5gOlicru0OHYrSuWvomTwyQSNBZIxzHDta4WSL3sHQ03FwvZUXdzi7xxsKncTPRvLGk85IQbMd6tB4FqvKmVxYs9kRFACIiAIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiA8KE2h2cpsQi4VREHWvlcNHsPa1/Tw5HqFNoik07XYMUqcExfAHOnpHunpL3c2xcAP04+n1m+u3JWvZnefQ1do5j5PLoLPPzZPdJyHrt61f1Rtqt21FXZpGDgTHXOxoyuP6cfI+IsfFbrJCeprfyv/StNdF3a4EXBBBHO9xZeywSWmx7ADdjnupwebbyw272nWP2eKnsH3zMIDaulcD+fE4OB/wAN5Fv8xSXjSq4u19ByXs15eFTqXeXhEg/rWQ9j4pGkevLb2rkxfejhkLCYpHTvscrGMc0E9LveAAPC/gs1hyN1xZNop+12JjD9pGVTTZpbFxu9j25H3/VAPiAtqzjtX5RxzFZayokqZfTkdcgcgOTWjuAAHqX6ewaM+SwZwc/AjzfWyDN7brp8nEko33REWSiIi4ywREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREB6kKoY9u9w2su50PCkPN8JyG/e22V3iRdEUwnJPTIZQcW3PTMuaerjcBfSRjmEfrNzX+4Kh1OAyxuyF0ZN+hdb3Ii9Xxss5J2ykjQ9hd2Je6OrqpY3RaPZEzMcxHLOSBYdwvftWzWRF52ecpTdl49H//Z

**Comment by RaresCode** [comment]
Fixed logo link
