### ISSUE TITLE
 Tremend - the message "Romania, Brasov is not a city in Romania" and other like this is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#461]
ENVIRONMENT: PRODUCTION
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Tremend" Company
3. Check the location for this jobs: 

- Office Administrator - Part Time
- Office Administrator - Part Time
- People Strategy Manager
- People Strategy Manager
- Staffing Partner

EXPECTED RESULTS:
The location for the jobs:
- Office Administrator - Part Time is Brasov
- Office Administrator - Part Time is Iasi
- Staffing Partner is Bucuresti 
according to the company's website

The location for this jobs:
- People Strategy Manager 
- People Strategy Manager
it is not important for us

ACTUAL RESULTS:
1. The messages "Romania, Brasov is not a city in Romania", "Romania, Iasi is not a city in Romania" and "Romania, Bucuresti is not a city in Romania" is displayed on the https://scrapers.peviitor.ro/src/tremend
2. According to SOLR, there are still 6 jobs located in Bucharest, and all remaining up to 73 are Remote, although Romania appears at the country, the location is not established.

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/a64bebd4-803d-4e56-9581-e5210213b89a)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/fc6ba678-f502-438f-8eb8-947bbd9822be)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/601cf9bb-ae79-49ef-a646-2afd5e816998)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/6cc788d7-b85e-4a3d-8ae8-ba390971de8d)

**Comment by lalalaurentiu** [comment]
Fixed
