### ISSUE TITLE
Teleperformance- Missing job type for all jobs/ for 1 job, remote is displayed in location section

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#462]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/teleperformance/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on 'Run scraper' button
3. Check job type for all jobs
4. Open https://www.teleperformance.com/en-us/careers/job-opportunities/
5. Check job type for all jobs

EXPECTED RESULTS:
All jobs on scrapers.peviitor.ro should have job type as it is on company website

ACTUAL RESULTS:
'No job type' is displayed on job type section for all jobs on scrapers.peviitor.ro

![a44](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/9382a608-cc57-43bc-8a99-05fbbb6f0678)

![a45](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/280092e9-9ffc-4f93-8394-48df8343a882)

**Comment by lalalaurentiu** [comment]
The job no longer available

**Comment by AdiVanca** [comment]
After retesting , there are 2 more jobs available where the job type is not specified on the scraper. ( one can work from home and the other from the office) 


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/8d14f566-156f-4294-8e6f-71437cc63876)
