### ISSUE TITLE
Weatherford - Status "Inactive" and No data in Local Storage

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#464]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open the URL in the browser
2. Search for "Weatherford" Company
3. Run scraper
4. Check the "Status" section
5. Check Local Storage

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section and Local Storage display all data

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section
The scraper doesn't return data in Local Storage
 On the company's website are displayed 6 jobs and  all of them located in Ploiesti (executed Q on SOLR)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/c78ade46-2937-44ba-97bd-c5e746a62d6a)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/bf41dfb6-8e8e-4c8d-a4c3-cbadc32b49d9)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/7d8aeae5-7501-4b5b-8216-60d3d5467088)

**Comment by lalalaurentiu** [comment]
Scraper is working
![Screenshot 2024-02-10 at 16 52 18 (2)](https://github.com/peviitor-ro/based_scraper_py/assets/67306273/d1459599-50b5-4496-9743-29f681d78cae)
