### ISSUE TITLE
Telusinternational - Missing "Targetare.ro" button

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#468]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Telusinternational " company
3. Go to logo - Click on Targetare.ro
4. Check "Targetare.ro" button
5. Check the " Careers" button

EXPECTED RESULTS:
The "Targetare.ro" button is functional . Targetare link opens correctly
The "Careers" button is displayed correctly

ACTUAL RESULTS:
Missing "Targetare.ro" button. Targetare link doesn't open targetare.ro
Next to the "Careers" button, the name of the company should not be displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/23dd13c3-e11b-4e34-a4f8-cdc61d66c4a0)

**Comment by lalalaurentiu** [comment]
Check on "targetare.ro" if it exists
