### ISSUE TITLE
Cartofisserie - The message "Bucuresti, Craiova, Satu-Mare, Suceava, Targu-Mures, Piatra Neamt is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#469]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Cartofisserie" Company
3. Check the location for the job: "LUCRATOR COMERCIAL / AJUTOR BUCATAR"

EXPECTED RESULTS:
The location for this job is located in several cities according to the company's website: Bucuresti, Craiova, Piatra Neamt, Satu-Mare, Targu-Mures, Suceava.

ACTUAL RESULTS:
On scrapers.peviitor.ro the message "Bucuresti, Craiova, Satu-Mare, Suceava, Targu-Mures, Piatra Neamt is not a city in Romania" is displayed for this job

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/320a1aad-1f5e-478e-a66e-7a269a5a6b69)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/1f34fc80-0d4e-4eef-a7cd-3dea0654ad36)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdinaIT** [comment]
Retesting: 
- Run scraper : On the https://scrapers.peviitor.ro/src/cartofisserie and also on the company's wesite https://www.ejobs.ro/user/locuri-de-munca/lucrator-comercial-ajutor-bucatar , the localities match with the counties
- Execute Query in SOLR: the county is displayed  incorrectly; appears Alba instead of Galati


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/1ca7b2bf-575e-4f3b-af00-0609bddd394e)

![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/dc339143-9866-429b-bce7-0a7badb551a2)

![Image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/88a09478-e5f2-461a-b6dd-e783b451361a)
