### ISSUE TITLE
Bayern -  On the scrapers.peviitor.ro missing the location for the job: "General Management & Business Consulting"

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#470]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Bayern" Company
3. Check the location for the job: "General Management & Business Consulting"

EXPECTED RESULTS:
The location for this job is in Romania, Bucuresti, Sintesti - Ialomita County according to the company's website.
This job is displayed on the Scrapers.peviitor.ro

ACTUAL RESULTS:
- On the scrapers.peviitor.ro  this job is not displayed
- It dispalyed with this name "General Management & Business Consulting" only on the companies' website
- Executed "fq" in SOLR and location was found in: Romania, Bucuresti, Sintesti - Ialomita County
- On the firme.peviitor.ro is displayed the massage: "Jobs in Romania - 1 position"
- On the scrapers.peviitor.ro there are 752 jobs with locations in other countries. Should be deleted, don't help us

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/9fd7806a-920e-4fd0-93d8-afe92b9d80ca)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/5dd14fd2-e04d-4f3a-8906-fac1137812c4)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/305c3b2a-5fbb-4c0c-a5e2-3729319097f6)

**Comment by lalalaurentiu** [comment]
Fixed
