### ISSUE TITLE
Cat - "Inactive" status;  No data in Local Storage; Error message 

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#472]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Cat" Company
3. Check the "Status" section
4. Chek the "Jobs" section
5. Check Local Storage
6. Go to logo -> Click on Careers

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section
The scraper displayed correctly Jobs number
Local Storage display all data
Careers link opens correctly

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section
Jobs numer is uknown
The scraper does not return data in Local Storage; Error message is displayed
Careers link open career section, but the message "The requested page "/ro-ro/articole/resurse-umane" could not be found." is displayed  
On https://peviitor.ro there are displayed 12 jobs

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/f19840c8-f3fa-45c2-9c53-2a648ac409d3)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/a97a9b41-1b43-4641-9bca-7c957498b837)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/ebbfb6f9-4be6-42f8-9fd2-b7e9af654384)

**Comment by lalalaurentiu** [comment]
i don't see any problem, scraper work fine

**Comment by AdinaIT** [comment]
Retesting. Scraper work fine
