### ISSUE TITLE
Dedeman- Satu-Mare and Targu Mures are not recognized as cities in Romania

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#473]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/dedeman/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on "Run scraper" button
3. Check job locations

EXPECTED RESULTS:
Satu Mare and Târgu Mureș are recognized as cities in Romania

ACTUAL RESULTS:
The scraper does not recognize 'Satu-Mare' and "Targu Mures"  as  cities in Romania
The message "Satu-Mare is not a city in Romania" and "Targu Mures is not a city in Romania" is displayed on scrapers.peviitor.ro

![a52](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/aabf0c1e-842d-4ebd-ac29-69e501b59673)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting Satu Mare and Târgu Mureș are recognizeed as cities in Romania
