### ISSUE TITLE
AllianzTiriac- The current careers link does not send you to the correct url

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#476]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/allianztiriac/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Go and click on 'Careers' link
4) Compare the jobs uploaded by the "Run scraper" button with the jobs found in the careers section

EXPECTED RESULTS:
The 'Careers' link should be https://www.allianztiriac.ro/ro_RO/cariere/cariere-posturi-disponibile.html#TabVerticalNegative11694447096 , where are found all open jobs

ACTUAL RESULTS:
The current 'Careers' link is https://www.allianztiriac.ro/en_RO/individuals/careers/open-positions.html
Not all open jobs can be found at the current link

![a53](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/36762efa-09a8-43ed-bcda-fdf6c65197a8)

![a54](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/b4218b61-5492-4ca8-aa33-649d356a1d76)

**Comment by lalalaurentiu** [comment]
Fixed
