### ISSUE TITLE
Betfair - 'ROMANIA REMOTE is not a city in Romania' is displayed on scrapers

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#478]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/betfair/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Check  location  and job type for  Java Developer - FanDuel job

EXPECTED RESULTS:
Job type should be remote and location  should be empty

ACTUAL RESULTS:
'ROMANIA REMOTE is not a city in Romania' is displayed on scrapers.peviitor

![Snip - Scraper-Betfair - Google Chrome](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6af60309-994e-4dbc-ae7b-32ac4e56effb)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting 'ROMANIA REMOTE is not a city in Romania' is no longer displayed on scrapers.


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/462be8d7-32c0-40f6-941b-c7fd5a10efc7)
