### ISSUE TITLE
Danone - Missing job type for all jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#479]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/danone/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Check job type for all loaded jobs 
4) Check job type for all jobs on company website

EXPECTED RESULTS:
Job type for all jobs should be specified as on company website (on-site or hybrid)

ACTUAL RESULTS:
'No job type' is displayed on scrapers.peviitor

![a57](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/3527fa66-11be-4d6b-ad58-8aba87231cc5)

![Snip - Job Details - Google Chrome](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/eb2cc58c-006b-42d6-99ca-7695078b4088)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting all jobs have job type specified as it is on company website
