### ISSUE TITLE
Brd - No job type specified for jobs in IT category

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#481]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/brd/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button 
3) Check job type for jobs  on scrapers
4) Check job type for jobs in IT category on company website

EXPECTED RESULTS:
 The jobs from IT category should have job type hybrid on scrapers as it is on company website

ACTUAL RESULTS:
The jobs from IT category have no job type specified 

https://github.com/peviitor-ro/based_scraper_py/assets/72222644/be57658e-c081-40fb-9cff-021bd40c8875

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting there are still jobs without job type posted on scrapers


![Image](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/aed62986-a6f9-42e0-a716-72a223115ba8)
