### ISSUE TITLE
Decathlon - the Scrapers doesn't return the real data for the "job type"

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#484]
ENVIROMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Run scraper for "Decathlon" Company
3. Check "job type" for all jobs on the https://apply.workable.com/decathlon-romania/ 

EXPECTED RESULTS:
The "job type" for all jobs should be the same as on company website

ACTUAL RESULTS:
On the scrapers.peviitor.ro for all the jobs the data job type is:  "No job type" while on the company website "job type" is : "Hybrid or On-Site"
The company type job aren't returned by the scraper

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/6124b2cf-fe5b-4d2d-a3fb-cfdfdf9ea154)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/04a26a49-1ad2-49ff-a0cd-438b3f3a83f3)

**Comment by lalalaurentiu** [comment]
Fixed
