### ISSUE TITLE
Acrom - Missing "Targetare.ro" button

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#485]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Acrom " Company
3. Go to logo - Click on Targetare.ro
4. Verify "Targetare.ro" button

EXPECTED RESULTS:
The "Targetare.ro" button is functional . Targetare link opens correctly

ACTUAL RESULTS:
Missing "Targetare.ro" button. Targetare link doesn't open targetare.ro

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/c1629928-896f-418d-a877-888bc5d0d994)

**Comment by lalalaurentiu** [comment]
did you search on "targetare.ro" to see if it exists?

**Comment by AdinaIT** [comment]
- when checking I found this: 

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/4d183931-1026-4d2c-9b9f-43ede39a29b4)
- which of them is real?

- I have noticed (for many times) that the name of a company on the scraper doesn't matching with the name on https://targetare.ro/cauta-firme

**Comment by lalalaurentiu** [comment]
none of them

**Comment by lalalaurentiu** [comment]
close this is invalid
