### ISSUE TITLE
LSEG - EROARE LA RULAREA LSEG.PY

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#5]
1) {
    "error": [
        "Traceback (most recent call last):",
        "  File \"lseg.py\", line 31, in <module>",
        "    job_link = \"[https://refinitiv.wd3.myworkdayjobs.com/en-US/Careers\](https://refinitiv.wd3.myworkdayjobs.com/en-US/Careers%5C)" + job.get(\"externalPath\")",
        "TypeError: can only concatenate str (not \"NoneType\") to str",
        ""
    ]

}

2) Din acest motiv este posibil sa nici nu actualizeze numarul de joburi: la noi 140 la ei pe site 139 pe Romania.

3) Logoul este modificat in unele sectiuni ale site-ul lor, adica este colorat in culorile lgbtq. Logoul de pe site-ul nostru este la fel cu cel din sectiunea lor de cariere, care nu are un logo actualizat fiind un serviciu externalizat,

**Comment by lalalaurentiu** [comment]
Lseg are momente când funcționeaza, ![image](https://github.com/peviitor-ro/based_scraper_py/assets/67306273/209ee6e4-6c95-4f6e-96f6-0ebde6325cdb), la pornirea scraperelor de către github actions a rulat in Api, te rog sa-l mai verifici o data.

**Comment by PravatMihaiGabriel** [comment]
L-am mai rulat inca o data si mi-a dat aceeasi eroare, dar la a doua rulare a mers.

Si ei au cateva posturi cu 2 locatii din care una in Romania si cealalta in alta tara.

Putem considera bugul rezolvat ?

**Comment by lalalaurentiu** [comment]
Toate scraperele care au probleme, fie ele si minore, nu le inchidem.

**Comment by lalalaurentiu** [comment]
Fixed
No more problems
<img width="1440" alt="Screenshot 2023-08-11 at 17 00 20" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/32d124a1-e467-49c6-983c-d03887d94811">
