### ISSUE TITLE
Zentiva -  On scrapers.peviitor.ro the message "Sofia is not a city in Romania" is displayed. 

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#506]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Zentiva" Company
3.Check the location for the jobs: "Supply Planner`s Team Lead"
4. Check the location of answered job after performing the query filter on SOLR

EXPECTED RESULTS:
On the company website, the location for this job is also in Bucharest / Romania

ACTUAL RESULTS:
The message "Sofia is not a city in Romania" is displayed on scrapers.peviitor.ro 
The location of the job after performing the query filter on SOLAR is Sofia and the country Romania

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/07d4ec72-77aa-417e-830a-63679ecc3b1e)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/76d0f1ff-ddbb-4f76-b8e7-3f4611854f92)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/94c43fbd-816f-48b6-9ae9-1cb655923888)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/15a525e9-e3e2-4660-846f-09caa48851bc)

**Comment by lalalaurentiu** [comment]
Fixed
