### ISSUE TITLE
Veeam - Missing job type (hybrid) for 2 jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#518]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/veeam/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Check job type on scrapers for : -Sales Development Representative (Entry Level) - with Italian 
                                    -Sales Development Representative with Turkish language (Entry Level) 

4) Check job type on company website for: -Sales Development Representative (Entry Level) - with Italian 
                                                                      - Sales Development Representative with Turkish language (Entry Level)

EXPECTED RESULTS:
Job type for 'Sales Development Representative (Entry Level) - with Italian'  and for 'Sales Development Representative with Turkish language (Entry Level)' should be hybrid as it is on company website

ACTUAL RESULTS:
In the "job type" section on scrapers "no job type" is displayed

![veeam](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/f4a3e8dc-d4b3-44a5-ada2-4a1967e0b056)

![veeam2](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/6883fd73-87d6-4755-a9ef-b0cd2e7cf80c)

**Comment by lalalaurentiu** [comment]
Deprecated!
