### ISSUE TITLE
Bcr - Job type not specified for 6 jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#520]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/bcr/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper' button
3) Check job type on scrapers for:
         - Data Science Specialist
         - Product Manager - Bancassurance
         - Senior Analyst
         - Consilier Juridic (Litigii)
         - Specialist Investigatii Senior
         - Compliance Expert (Regulatory Control)
4) Check job type on company website for the same jobs from stem 3

EXPECTED RESULTS:
The jobs on scrapers should have specified job type as it is on company website

ACTUAL RESULTS:
The job type is missing on scrapers for:
         - Data Science Specialist
         - Product Manager - Bancassurance
         - Senior Analyst
         - Consilier Juridic (Litigii)
         - Specialist Investigatii Senior
         - Compliance Expert (Regulatory Control)

![bcr](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/2bba7879-87fd-4078-8722-7fbe83a7751f)

**Comment by lalalaurentiu** [comment]
Deprecated!
