### ISSUE TITLE
Lseg - Bucuresti appears twice as location

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#521]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/lseg/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper'
3) Check location for Senior Analyst - Global Share Plans

EXPECTED RESULTS:
Bucuresti should appear only once as location for Senior Analyst - Global Share Plans

ACTUAL RESULTS:
Bucuresti appears twice as location for Senior Analyst - Global Share Plans

![lseg](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/60d724bc-18da-4231-b3fd-710f9d61a30f)

**Comment by lalalaurentiu** [comment]
Deprecated!
