### ISSUE TITLE
UPS -the message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#524]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Run scraper for "Ups" company
3. Check the location for the job: "Air Ramp Specialist" 
4. Check the job numer on the https://peviitor.ro

EXPECTED RESULTS:
The location for the jobs "Air Ramp Specialist" is displayed (Bucuresti)
The number of jobs is the same on scrapers.peviitor.ro as on the peviitor.ro

ACTUAL RESULTS:
On scrapers.peviitor.ro for the job "Air Ramp Specialist, the message: "Romania is not a city in Romania" is displayed
The number of jobs posted on scrapers.peviitor.ro (1) is not the same as the number of jobs posted on the peviitor.ro (3)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/82bd5890-be40-4915-be4b-1e93a2bb0534)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/71bac0fe-8e88-4a5e-a01d-a95f6802e618)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/982db77b-6c32-443d-aa46-c9dbe07c4d32)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/9e00c9bd-da98-4ad5-9edd-5ad60d0102bd)

**Comment by lalalaurentiu** [comment]
Deprecated!
