### ISSUE TITLE
Bancatransilvania - Incomplete location for 1 job and '805200-Targu-Bujor is not a city in Romania' is displayed on scrapers

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/based_scraper_py#525]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/bancatransilvania/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Click on 'Run scraper'
3) Check location on scrapers for: Specialist Servicii Clienti and for Manager Relatii Clienti Persoane Fizice - Targu Bujor
4) Check location on company website for: Specialist Servicii Clienti and for Manager Relatii Clienti Persoane Fizice - Targu Bujor

EXPECTED RESULTS:
The location for 'Specialist Servicii Clienti' should be complete as it is on company website and for 'Manager Relatii Clienti Persoane Fizice - Targu Bujor' should be 'Targu Bujor

ACTUAL RESULTS:
'445200-Negresti-Oas is not a city in Romania' and '805200-Targu-Bujor is not a city in Romania' is displayed on scrapers as location

![banca](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/602066b9-d0a8-4594-a55e-e96461bd6f7d)

![banca2](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/1404dfb6-9a7f-42e0-9378-d52529f13c3d)

**Comment by lalalaurentiu** [comment]
Deprecated!
