### ISSUE TITLE
Synevo - On Scrapers UI the number of jobs aren't displayed

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#526]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Synevo" Company
3. Check the jobs
4. Open https://www.synevo.ro/cariere
5. Check the jobs

EXPECTED RESULTS:
Jobs are uploaded on ScrapersUI because there are active job on the company website

ACTUAL RESULTS:
No jobs are currently displayed on ScrapersUI
On SOLR and peviitor.ro the number of jobs aren't displayed
On company website the number of jobs are displayed

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/05b4ac39-fddc-4013-81b0-9fadce341373)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/cb147a27-10ea-40a0-aace-55b729d95488)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/dfdcda46-e6bc-48f1-8640-145412720436)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/b409575a-39d6-4749-b680-6605f50d8562)

**Comment by lalalaurentiu** [comment]
Deprecated!
