### ISSUE TITLE
Vodafone - Job title incomplete - Service Manager

### ISSUE THREAD

**Issue by Fulger19** [peviitor-ro/based_scraper_py#54]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type Vodafone in search bar
3) Search for the job title "Service"
4) Click on "Vezi postul"
5) Check the title of job posting

EXPECTED RESULTS:
The job title should be the same as on Vodafone website
https://jobs.vodafone.com/careers/job/563018677256127-service-manager-bucuresti-rou?domain=vodafone.com

ACTUAL RESULTS:
Job title is different than the job title on Vodafone website
"Service" is displayed instead of "Service Manager"

![image](https://github.com/peviitor-ro/based_scraper_py/assets/135150028/c63d943b-3b92-4b3e-a175-dc3f6867de8a)

**Comment by TheMrM** [comment]
Fixed. Title should be shown as in JD - job description.
Let me know if you encounter new bugs.
As of 04/08/2023 22:30 it works correctly and will add Fixed. Issue will still be open.
