### ISSUE TITLE
Scraper for Dedeman is not running

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/based_scraper_py#574]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Click on "Scraperi".
3. Click on "based_scraper_py".
4. Write "Dedeman" in the search bar and press enter. 
5. Run the scraper.

**EXPECTED RESULTS:**
The scraper runs without issues.

**ACTUAL RESULTS:**
The scraper is running, but an error pops up.

![image](https://github.com/user-attachments/assets/65f74918-151c-456b-b8ee-975abca15694)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Lore78** [comment]
Thanks a lot 🙏

sâm., 23 nov. 2024, 02:50 Baluta Laurentiu Marian ***@***.***>
a scris:

**Comment by Lore78** [comment]
Retested and OK
