### ISSUE TITLE
"Allianz" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/based_scraper_py#575]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Allianz"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since 12 September.

![image](https://github.com/user-attachments/assets/9f047503-2bc0-4c9f-9331-3d5beeecd9ac)

![image](https://github.com/user-attachments/assets/78a12302-d9b8-4e9a-8f75-1e1e1f9944f4)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
