### ISSUE TITLE
"Autonom" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/based_scraper_py#576]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Autonom"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since 18 September.

![image](https://github.com/user-attachments/assets/46ec39f3-2264-48c4-8a5f-cfb80fa3ccee)

![image](https://github.com/user-attachments/assets/8bdb1ed6-f30b-4a9a-b02f-b667c621d4bc)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
