### ISSUE TITLE
"Draxlmaier" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/based_scraper_py#577]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Draxlmaier"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since 19 September.

![image](https://github.com/user-attachments/assets/be664bd7-8ec7-483e-9a9b-e9554a112794)

![image](https://github.com/user-attachments/assets/eb329e24-4dd7-46af-b3fb-0c37fdb4a6e0)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
