### ISSUE TITLE
PPT - duplicate jobs

### ISSUE THREAD

**Issue by Fulger19** [peviitor-ro/based_scraper_py#58]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type the name of the company in the search bar
3) Check the number of jobs available for the company
4) Click on "Vezi postul"
5) Check the title of job posting

EXPECTED RESULTS:
The number of jobs posted on the URL for the company should be the same like the number of jobs posted on the company website on the careers section.

ACTUAL RESULTS:
The number of jobs posted on the URL for the company is 12, and the number of jobs posted on the company website (ejobs) on the careers section is 6.
The jobs are being duplicated as per print screen attached.

1. Stivuitorist (depozit PPT - com. Maracineni) - appearing twice for the same city

2. Trainer & Asistent magazine PPT - appearing twice for the same cities

3. Casier appearing 6 times 
- positions 1 and 3 are for the cities Beius, Bistrita, Deja, Sighetu Marmatiei, Timisoara, 
- positions 2 and 4 are for the cities Arad, Medgidia, Medias, Sebes, Zalau, 
- positions 5 and 6 are for different cities - no problem with the last two positions for ”casier”.

![ppt](https://github.com/peviitor-ro/based_scraper_py/assets/135150028/bcab353c-0772-4219-ae5d-220e56df2688)

**Comment by TheMrM** [comment]
New scraper takes correctly the jobs and dose not duplicate them anymore.
