### ISSUE TITLE
Jacobsdouweegberts - "Editati" and "Stergeti" buttons not functional

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/based_scraper_py#580]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

 
### **STEPS TO REPRODUCE:**
1) Type "Jacobsdouweegberts" in the search field
2) Click on "Vizualizeaza Joburi" button
3) Navigate to "Accounting Specialist" job listing
4) Click on "Editati" button
5) Select "hybrid" from the job type list
6) Click on "Editati" button
7) Click on the "x" icon to close the popup window
8) Click on "Stergeti" button

>**EXPECTED RESULTS:**
The new values are added to the job listing details.
Job listing is deleted from the list.

>**ACTUAL RESULTS:**
The freshly inserted values are not being saved. 
The popup window will not close unless clicking on the "x" icon. 
Clicking the "x" icon does not save the new values.
Clicking the "Stergeti" button does not delete the job listing.
Job remains active in the list and in production.

![image](https://github.com/user-attachments/assets/69bc819d-f200-4c60-9d1f-a256151cb4c8)

![image](https://github.com/user-attachments/assets/70c992fc-fc1a-403b-a6e4-15f5a9b27138)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
