### ISSUE TITLE
"Ptc" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/based_scraper_py#584]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Ptc"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since 23 September.

![image](https://github.com/user-attachments/assets/ac002c00-2388-4307-8bd9-aeaafe177f88)

![image](https://github.com/user-attachments/assets/892464ae-2478-4f2c-8158-dcc1975f9ad5)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
