### ISSUE TITLE
Number of jobs from the "Decathlon" website does not correspond to the number of jobs in the validator 

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/based_scraper_py#586]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Preconditions:
Have the https://admin.peviitor.ro/ page opened.

STEPS TO REPRODUCE:
1) Click on "Scraperi".
2) Type "Decathlon" in the search bar.
3) Click on the "Cauta" button. 
4) Find "decathlon.py" and run it. 
5) Click on "Companii".
6) Type "Decathlon" in the search bar.
7) Check the number of jobs available for the company.
8) Open the careers section of the company website.
9) Check the number of jobs available.
10) Compare it with the number of jobs from the URL.

EXPECTED RESULTS:
The number of jobs posted on the URL for the company should be the same as the number of jobs posted on the company website on the careers section.

ACTUAL RESULTS:
The number of jobs posted on the URL for the company is 90 and the number of jobs posted on the company website on the careers section is 95.

![image](https://github.com/user-attachments/assets/d0672ce1-6c3a-44f6-93f8-8b26a5e47198)

![image](https://github.com/user-attachments/assets/61863b51-fec9-493b-902c-f0d923ea44dd)

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by Lore78** [comment]
Fixed!

![image](https://github.com/user-attachments/assets/29224831-f05c-4d8f-b94f-c2092472a12b)

![image](https://github.com/user-attachments/assets/62acf806-ccaf-4081-9884-9aba42440313)
