### ISSUE TITLE
Romaero - Job title incomplete - FUNCȚIONAR ÎN ACTIVITĂȚI COMERCIALE, ADMINISTRATIVE ȘI PREȚURI

### ISSUE THREAD

**Issue by Fulger19** [peviitor-ro/based_scraper_py#59]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type Romaero in search bar
3) Search for the job title "FUNC"
4) click on "Vezi postul"
5) check the title of job posting

EXPECTED RESULTS:
The job title should be the same as on Romaero website
https://romaero.com/cariere/anunt-angajare-functionar-in-activitati-comerciale-administrative-si-preturi/

ACTUAL RESULTS:
Job title is different than the job title on Romaero website
"FUNC" is displayed instead of "FUNCȚIONAR ÎN ACTIVITĂȚI COMERCIALE, ADMINISTRATIVE ȘI PREȚURI"

![image](https://github.com/peviitor-ro/based_scraper_py/assets/135150028/e5ba3c4d-3c2f-4e18-8a1f-75c0c3a817fe)

**Comment by lalalaurentiu** [comment]
Fixed!
