### ISSUE TITLE
Vodafone- job Technical Lead 1st Line De does not exist on the official site.

### ISSUE THREAD

**Issue by HDanaA** [peviitor-ro/based_scraper_py#64]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Microsoft Edge
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type Vodafone in the search bar
3) Click ,,Incarca mai multe,, until there are displayed all of the jobs from Vodafone site.
3) Search for the job title Technical Lead 1st Line De
4) Click  ,,Vezi Postul,, 

EXPECTED RESULTS:
The job should be displayed on URL: https://jobs.vodafone.com/careers/job/563018677144032-technical-lead-1st-line-de-bucuresti-rou?domain=vodafone.com

ACTUAL RESULTS:
The job does not exist on the Vodafone site.
And the below message is displayed.
![error vodafone](https://github.com/peviitor-ro/based_scraper_py/assets/141658361/4d8e781e-1025-4e5a-8eb8-4db9b1af24ee)

**Comment by lalalaurentiu** [comment]
Fixed
