### ISSUE TITLE
Vodafone-job Team Leader Agile Project Delivery does not exist on the official site.

### ISSUE THREAD

**Issue by HDanaA** [peviitor-ro/based_scraper_py#65]
Environment: Production
URL: https://peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Type the job title Team Leader Agile Project Delivery in the search bar.
3. Click ,,Cauta,,
4. Click ,,Vezi Postul,,  on the job with the title Team Leader Agile Project Delivery from Vodafone.

EXPECTED RESULTS:
The job should be displayed on URL: https://jobs.vodafone.com/careers/job/563018677094943-team-leader-agile-project-delivery-bucuresti-rou?domain=vodafone.com

ACTUAL RESULTS:
The job does not exist on the Vodafone site.
And the below message is displayed.
![error vodafone](https://github.com/peviitor-ro/based_scraper_py/assets/141658361/8143c83e-4ee4-4cde-8fc9-8f6571aeea28)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by HDanaA** [comment]
the bug was retested
