### ISSUE TITLE
AllianzTiriac - The number of jobs on peviitor.ro is different from the AllianzTiriac career website and from the API

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#66]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type AllianzTiriac in the search bar
3) Check the number of jobs available for AllianzTiriac

EXPECTED RESULTS:
The number of jobs posted on the URL for AllianzTiriac should be the same like the number of jobs returned by pe API and the number of jobs posted on the AllianzTiriac website on the careers section.

ACTUAL RESULTS:
The number of jobs posted on the URL for AllianzTiriac is 6 the number of jobs returned by the API is 7 and the number of jobs posted on the AllianzTiriac website on the careers section is 7 but one is doubled on 2 different categories (https://www.allianztiriac.ro/ro_RO/cariere.html).

**Comment by lalalaurentiu** [comment]
Where is the problem? The api returns 13 jobs, if you count the jobs from the AllianzTiriac careers page, they are the same

<img width="1440" alt="Screenshot 2023-08-09 at 23 17 40" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/333e7900-de8b-43fd-8407-fc71dc62a779">


<img width="1440" alt="Screenshot 2023-08-09 at 23 19 23" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/a1af9a5d-d768-4eeb-8ca6-acd6495d3db8">

<img width="1440" alt="Screenshot 2023-08-09 at 23 26 02" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/5a8bf573-8543-4653-8582-ad3249f14087">

<img width="1440" alt="Screenshot 2023-08-09 at 23 25 54" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/959c2537-cfe3-43fa-9517-22dbfdb15912">

<img width="1440" alt="Screenshot 2023-08-09 at 23 25 59" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/2c4e9630-c8dc-42d0-9e93-310ab74bfb38">

<img width="1440" alt="Screenshot 2023-08-09 at 23 25 51" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/2f5414c9-1128-4ff2-80ed-4ed89061e025">

<img width="1440" alt="Screenshot 2023-08-09 at 23 25 44" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/1ee93c8d-56e8-4e88-ab58-3f0008f3380f">

<img width="1440" alt="Screenshot 2023-08-09 at 23 25 34" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/0b407a4f-ca5d-4e65-9e03-ffcf8adf0dae">

**Comment by PravatMihaiGabriel** [comment]
Now it looks fine. Earlier it did not show the same results. I will attach pictures in the future.
