### ISSUE TITLE
Betfair - The number of jobs on peviitor.ro is different from the Betfair career website and from the API

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#67]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type Betfair in the search bar
3) Press Enter
4) Check the number of jobs available for Betfair

EXPECTED RESULTS:
The number of jobs posted on the URL for Betfair should be the same as the number of jobs returned by the API and the number of jobs posted on Betfair website on the careers section.

ACTUAL RESULTS:
The number of jobs posted on the URL for Betfair is 77, the number of jobs returned by the API is 77 and the number of jobs posted on Betfair website on the careers section is 78 (https://www.betfairromania.ro/jobs/).

**Comment by lalalaurentiu** [comment]
Because 1 job is from another country.
<img width="1440" alt="Screenshot 2023-08-10 at 00 22 56" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/f622db7a-8435-454d-8f79-3c4ca796bbd9">
