### ISSUE TITLE
Linde

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#7]
Pe Romania sunt 13 locuri de munca sila ei si la noi, dar au aceasta pozitie https://linde.csod.com/ux/ats/careersite/20/home/requisition/10931?c=linde pentru care au 3 locuri disponibile in Romania, Portugalia si Spania.
Nu este bug pentru noi, mai degraba este pentru ei.

**Comment by lalalaurentiu** [comment]
Nu este bug, ci un job care este disponibil in mai multe locații.
