### ISSUE TITLE
Vodafone-job Tech Expert Mihalache does not exist on the official site.

### ISSUE THREAD

**Issue by HDanaA** [peviitor-ro/based_scraper_py#81]
Environment: Production
URL: https://peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Type the job title Tech Expert Mihalache in the search bar.
3. Click ,,Cauta,,
4. Click ,,Vezi Postul,, on the job with the title Tech Expert Mihalache from Vodafone.

EXPECTED RESULTS:
The job should be displayed on URL: https://jobs.vodafone.com/careers/job/563018677263700

ACTUAL RESULTS:
The job does not exist on the Vodafone site.
And the below message is displayed.
![error vodafone](https://github.com/peviitor-ro/based_scraper_py/assets/141658361/a486929f-d880-418d-ba92-184e5301bedd)

**Comment by lalalaurentiu** [comment]
The job was deleted after restarting the scraper

**Comment by HDanaA** [comment]
the bug was closed after retesting on 18.08
