### ISSUE TITLE
STRABAG - the number of jobs on the peviitor.ro should be the same with the one from Strabg careers website

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#88]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type STRABAG in the search bar
3) Check the number of jobs available for the company
3) Click on the button "Cauta"
4) 30 jobs available for STRABAG in the URL ( screenshot attached)
5) Open the careers section of STRABAG website ( https://jobboerse.strabag.at/jobs-overview.php?language=RO)
6) Type Romania in the search bar
7)  Click on the button "Cauta job-uri" 
8) 41 jobs available on STRABAG webite ( screenshot attached)

EXPECTED RESULTS:
The number of jobs posted on the URL for STRABAG should be the same like the number of jobs returned by STRABAG website on the careers section.
ACTUAL RESULTS:
The number of jobs posted on the URL for STRABAG is 30, and the number of jobs posted on STRABAG website on the careers section is 41
![Screenshot (311)](https://github.com/peviitor-ro/based_scraper_py/assets/35573782/8bf71d33-ceaa-4e74-9f2b-54485bbcf6d2)
![Screenshot (310)](https://github.com/peviitor-ro/based_scraper_py/assets/35573782/6b90140e-50f2-472c-9a11-5b0b646704cf)

**Comment by TheMrM** [comment]
As of 9/9/2023, 9:48 PM, the scraper successfully gets the 35 jobs that are posted on the main website for Romania. The issue will be closed.
