### ISSUE TITLE
Veeam - number of jobs differs from the one on Peviitor and API

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#89]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Veeam" in the search bar.
3. Check the number of jobs available for Veeam.
4. Run "Veeam" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 47 while the number of jobs returned by the API is 168.

![Veeam peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/c546923d-033b-4a02-bbc9-551aabf3a70a)

![Veeam API](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/1a768f97-b7f8-4e21-abc6-42755288d743)

**Comment by lalalaurentiu** [comment]
The script takes all jobs, select "Toate" and then compare them with the api's response

<img width="1440" alt="Screenshot 2023-09-07 at 19 40 54" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/a24934fa-fe5e-4506-bcb5-8e31d8ecd441">

<img width="1440" alt="Screenshot 2023-09-07 at 19 41 00" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/1ef10092-94c2-418a-b591-9acfcc251af6">

**Comment by TheMrM** [comment]
DUPLICATE ISSUE
