### ISSUE TITLE
Intel - logo diferit

### ISSUE THREAD

**Issue by PravatMihaiGabriel** [peviitor-ro/based_scraper_py#9]
Logoul este diferit de cel de pe siteul Intel
https://jobs.intel.com/en/job/timisoara/senior-deep-learning-software-engineer/41147/34505457888

**Comment by lalalaurentiu** [comment]
😂, l-am luat de pe net, am sa-l modific cu cel real.

**Comment by lalalaurentiu** [comment]
Done! dacă mai găsești ceva în neregula cu logo poți deschide din nou acest issues.
