### ISSUE TITLE
Amazon - the number of jobs posted on Peviitor isn't the same as the one posted on Amazon's website.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#91]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Amazon" in the search bar.
3. Check the number of jobs available for Amazon.
4. Open "https://www.amazon.jobs/en/search?base_query=&loc_query=Romania&country=ROU".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on "https://www.amazon.jobs/en/search?base_query=&loc_query=Romania&country=ROU" should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 26 while the number of jobs posted on the company website is 47.

![Amazon peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/b258e3ff-08e2-47e9-8ca4-ea04195bac72)

![amazon site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/944a4c16-a6b5-4e1e-a84e-6427f8475517)

**Comment by Ale230992** [comment]
Acum sunt 48 joburi pe site-ul Amazon si 49 pe site-ul Peviitor.

![amazon peviitor reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/134cd5e6-25fe-4fde-bfe1-2e59980d256f)

![amazon jobs site reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/da7a5e67-4589-431e-b86b-823b2df2c44e)

**Comment by lalalaurentiu** [comment]
Afiseaza 49 din cauza ca Un job de la HP are în descriere "Amazon"
<img width="1440" alt="Screenshot 2023-09-11 at 20 25 02" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/731deb72-1183-4de7-83fe-cd3682dfceae">
Aici nu mai e problema cu screperul poți mut bugul în acest repo [https://github.com/peviitor-ro/firme-peviitor](url)
