### ISSUE TITLE
UiPath - the number of jobs posted on Peviitor isn't the same as the one posted on UiPath's website.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#92]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "UiPath" in the search bar.
3. Check the number of jobs available for UiPath.
4. Open "https://careers.uipath.com/careers/jobs?location=romania&stretch=10&stretchUnit=MILES&page=1&limit=100&locationType=LAT_LNG".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on "https://careers.uipath.com/careers/jobs?location=romania&stretch=10&stretchUnit=MILES&page=1&limit=100&locationType=LAT_LNG" should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 29 while the number of jobs posted on "https://careers.uipath.com/careers/jobs?location=romania&stretch=10&stretchUnit=MILES&page=1&limit=100&locationType=LAT_LNG" is 27.

![uipath peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/0237aa5e-1527-472a-9fb0-ab784a96d6da)

**Comment by lalalaurentiu** [comment]
Deselect "no" to get all jobs
<img width="1440" alt="Screenshot 2023-09-08 at 18 48 29" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/e0682f5e-190e-40b2-9347-f14b1bf03aa1">
